import { defineConfig, type UserConfig } from 'tsdown';

const config: UserConfig = defineConfig({
  entry: {
    index: 'src/index.ts',
    cache: 'src/entries/cache.ts',
    db: 'src/entries/db.ts',
    flow: 'src/entries/flow.ts',
    logger: 'src/entries/logger.ts',
    platform: 'src/entries/platform.ts',
    schema: 'src/entries/schema.ts',
    serializer: 'src/entries/serializer.ts',
    singleton: 'src/entries/singleton.ts',
    // The `lilypad-doctor` command (package.json `bin`)
    'lilypad-doctor': 'src/cli/lilypad-doctor.ts',
  },
  // ES modules only (.mjs/.d.mts): Node.js 22.12+ also loads them with require(). One format means
  // one copy of each class, so `instanceof` works whatever the importer. The modules shared by
  // several entries go to common chunks: every entry uses the same copy of each module
  format: ['esm'],
  // isolatedDeclarations (tsconfig.json) lets the declarations be generated by oxc, file by file
  dts: true,
  sourcemap: true,
  // Writes the `exports` and the `bin` of package.json from the entries: never edit them by hand
  exports: {
    exclude: ['lilypad-doctor'],
    bin: { 'lilypad-doctor': 'src/cli/lilypad-doctor.ts' },
  },
  // Checks of the package as it is published: its package.json, the resolution of its types, and
  // the dependencies it declares but does not use
  publint: { strict: true },
  attw: { profile: 'esm-only', level: 'error' },
  unused: { level: 'error' },
  outputOptions(options) {
    // Shared chunks go to a subfolder, so that dist/ lists only the entries
    const chunkFileNames = options.chunkFileNames;
    options.chunkFileNames =
      typeof chunkFileNames === 'function'
        ? (chunk) => `chunks/${chunkFileNames(chunk)}`
        : `chunks/${chunkFileNames}`;
    return options;
  },
});

export default config;
