import type { LilypadDbGate } from '@/dbGate/LilypadDbGate';

/**
 * The changelog records every change of the cached tables in a table, so that each instance can
 * read the changes made since its last check with one query. It needs no long-lived connection
 * (unlike `LISTEN/NOTIFY`), so it suits serverless platforms, and it also catches the changes made
 * by other programs. It needs PostgreSQL 13 or later (`xid8`).
 */
export const LILYPAD_DEFAULT_CHANGELOG_TABLE = 'lilypad_cache_changes';
export const LILYPAD_DEFAULT_NOTIFY_CHANNEL = 'cache_events';

/**
 * The version of the changelog table and trigger function generated by {@link lilypadChangelogSql}.
 * The function carries it in its comment (`lilypad-changelog:<version>`), so that
 * `checkLilypadSchema` can tell an installation made by an older version of the library.
 */
export const LILYPAD_CHANGELOG_VERSION = 3;
export const LILYPAD_CHANGELOG_VERSION_PREFIX = 'lilypad-changelog:';

/** Replaces the characters that are not allowed in the names derived from a table name. */
function identifierPrefix(name: string): string {
  return name.replace(/\W/g, '_');
}

/** Quotes an identifier; `schema.table` is quoted part by part. */
export function quoteIdentifier(identifier: string): string {
  return identifier
    .split('.')
    .map((part) => `"${part.replace(/"/g, '""')}"`)
    .join('.');
}

function quoteLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** The trigger function name for a changelog table. */
export function triggerFunctionName(changelogTable: string): string {
  return `${identifierPrefix(changelogTable)}_record`;
}

/** The names of the row trigger and of the TRUNCATE trigger that record the changes of a table. */
export function changelogTriggerNames(table: string): { row: string; truncate: string } {
  const prefix = identifierPrefix(table);
  return { row: `${prefix}_lilypad_changes`, truncate: `${prefix}_lilypad_truncate` };
}

export type LilypadChangelogSqlOptions = {
  /** Name of the changelog table. Defaults to `lilypad_cache_changes`. */
  table?: string;
  /**
   * Channel on which the trigger also sends a `NOTIFY` for the `listen` strategy, or `false` to
   * send none. Defaults to `cache_events`.
   */
  notifyChannel?: string | false;
};

/**
 * The SQL that creates the changelog table and its trigger function. Run it once, in a migration.
 * It is idempotent (`IF NOT EXISTS` / `CREATE OR REPLACE`).
 *
 * Then attach the trigger to every cached table with {@link lilypadChangelogTriggerSql}.
 */
export function lilypadChangelogSql(options: LilypadChangelogSqlOptions = {}): string {
  const table = options.table ?? LILYPAD_DEFAULT_CHANGELOG_TABLE;
  const channel = options.notifyChannel ?? LILYPAD_DEFAULT_NOTIFY_CHANNEL;
  const quotedTable = quoteIdentifier(table);
  const indexPrefix = identifierPrefix(table);
  const notify = (idExpression: string, opExpression: string) =>
    channel === false
      ? ''
      : `
    PERFORM pg_notify(${quoteLiteral(channel)}, json_build_object(
      'schema', TG_TABLE_SCHEMA, 'table', TG_TABLE_NAME, 'id', ${idExpression}, 'op', ${opExpression},
      'xid', pg_current_xact_id()::text
    )::text);`;
  const functionName = quoteIdentifier(triggerFunctionName(table));

  return `CREATE TABLE IF NOT EXISTS ${quotedTable} (
  id           bigserial   PRIMARY KEY,
  xid          xid8        NOT NULL DEFAULT pg_current_xact_id(),
  table_schema text,
  table_name   text        NOT NULL,
  row_id       text,
  op           text        NOT NULL,
  changed_at   timestamptz NOT NULL DEFAULT clock_timestamp()
);
-- Version 1 had no schema column: tables of the same name in different schemas were mixed up
ALTER TABLE ${quotedTable} ADD COLUMN IF NOT EXISTS table_schema text;
-- Version 3 records TRUNCATE, which concerns no single row
ALTER TABLE ${quotedTable} ALTER COLUMN row_id DROP NOT NULL;
CREATE INDEX IF NOT EXISTS ${quoteIdentifier(`${indexPrefix}_table_xid_idx`)}
  ON ${quotedTable} (table_name, xid);
CREATE INDEX IF NOT EXISTS ${quoteIdentifier(`${indexPrefix}_changed_at_idx`)}
  ON ${quotedTable} (changed_at);

-- Records a change of a row, or a TRUNCATE of the table; the trigger argument is the primary key column.
CREATE OR REPLACE FUNCTION ${functionName}() RETURNS trigger AS $$
DECLARE
  new_id text;
  old_id text;
BEGIN
  IF TG_OP = 'TRUNCATE' THEN
    INSERT INTO ${quotedTable} (table_schema, table_name, row_id, op)
      VALUES (TG_TABLE_SCHEMA, TG_TABLE_NAME, NULL, 'TRUNCATE');${notify('NULL', `'TRUNCATE'`)}
    RETURN NULL;
  END IF;

  IF TG_OP <> 'DELETE' THEN
    new_id := to_jsonb(NEW) ->> TG_ARGV[0];
  END IF;
  IF TG_OP <> 'INSERT' THEN
    old_id := to_jsonb(OLD) ->> TG_ARGV[0];
  END IF;

  -- An update that changes the primary key also deletes the old key
  IF TG_OP = 'UPDATE' AND old_id IS DISTINCT FROM new_id THEN
    INSERT INTO ${quotedTable} (table_schema, table_name, row_id, op)
      VALUES (TG_TABLE_SCHEMA, TG_TABLE_NAME, old_id, 'DELETE');${notify('old_id', `'DELETE'`)}
  END IF;

  INSERT INTO ${quotedTable} (table_schema, table_name, row_id, op)
    VALUES (TG_TABLE_SCHEMA, TG_TABLE_NAME, COALESCE(new_id, old_id), TG_OP);${notify('COALESCE(new_id, old_id)', 'TG_OP')}
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;
COMMENT ON FUNCTION ${functionName}() IS ${quoteLiteral(`${LILYPAD_CHANGELOG_VERSION_PREFIX}${LILYPAD_CHANGELOG_VERSION}`)};
`;
}

/**
 * The SQL that attaches the changelog triggers to a cached table: one for the changes of its rows,
 * and one for `TRUNCATE`, which fires no row trigger. Run it once per table, in a migration, after
 * {@link lilypadChangelogSql}.
 *
 * @param options.table - The cached table (as in its `LilypadDbSchema`).
 * @param options.primaryKey - Its primary key column.
 * @param options.changelogTable - The changelog table, if not the default one.
 */
export function lilypadChangelogTriggerSql(options: {
  table: string;
  primaryKey: string;
  changelogTable?: string;
}): string {
  const changelogTable = options.changelogTable ?? LILYPAD_DEFAULT_CHANGELOG_TABLE;
  const names = changelogTriggerNames(options.table);
  const table = quoteIdentifier(options.table);
  const execute = `EXECUTE FUNCTION ${quoteIdentifier(triggerFunctionName(changelogTable))}(${quoteLiteral(options.primaryKey)})`;
  return `DROP TRIGGER IF EXISTS ${quoteIdentifier(names.row)} ON ${table};
CREATE TRIGGER ${quoteIdentifier(names.row)}
  AFTER INSERT OR UPDATE OR DELETE ON ${table}
  FOR EACH ROW ${execute};
DROP TRIGGER IF EXISTS ${quoteIdentifier(names.truncate)} ON ${table};
CREATE TRIGGER ${quoteIdentifier(names.truncate)}
  AFTER TRUNCATE ON ${table}
  FOR EACH STATEMENT ${execute};
`;
}

/**
 * A change recorded by the changelog: a change of one row, or a `TRUNCATE` of the table (which
 * removed every row, and has no `rowId`).
 */
export type LilypadChange = {
  /** The id of the changelog row. */
  id: string;
  /** The transaction that made the change. */
  xid: bigint;
} & ({ rowId: string; op: 'INSERT' | 'UPDATE' | 'DELETE' } | { rowId: null; op: 'TRUNCATE' });

/**
 * Where the next read of the changelog starts: the transactions that a read could not see yet.
 * They are the ones still running when it read (`xip`) and the ones that had not started
 * (`xid >= xmax`): every other transaction had already committed or aborted, so its changes were
 * visible to that read.
 */
export type LilypadChangelogCursor = {
  /** The first transaction id not yet assigned when the read took its snapshot. */
  xmax: bigint;
  /** The transactions running when the read took its snapshot. */
  xip: bigint[];
};

/** What to read of a table: the changes since a cursor, or those of the last `lookback` ms. */
export type LilypadChangesRequest = {
  tableName: string;
  since: { cursor: LilypadChangelogCursor } | { lookback: number };
};

/**
 * Whether the changes of the transaction `xid` were visible to the read that produced `cursor`:
 * a later read from this cursor does not return them.
 */
export function lilypadCursorCovers(cursor: LilypadChangelogCursor, xid: bigint): boolean {
  return xid < cursor.xmax && !cursor.xip.includes(xid);
}

/**
 * Reads the changes of a table since `cursor`, and the cursor for the next read.
 *
 * The cursor holds the transactions the read could not see yet (see
 * {@link LilypadChangelogCursor}): the next read returns exactly the changes of those
 * transactions that are visible to it, whatever the order of the commits. Each change is thus
 * returned once, and a long-running transaction does not make every read return again all the
 * changes made since it started.
 *
 * Without a cursor (first read, or a cursor no longer trusted), `since.lookback` returns the
 * changes recorded in the last `lookback` milliseconds instead.
 *
 * `tableName` is resolved as the gate's queries resolve it (with the `search_path` when it is not
 * qualified), so a table of the same name in another schema is not mixed up with it. Rows recorded
 * by a version 1 trigger, which had no schema, match any schema.
 */
export async function readLilypadChanges(
  gate: LilypadDbGate,
  options: LilypadChangesRequest & { changelogTable?: string }
): Promise<{ changes: LilypadChange[]; cursor: LilypadChangelogCursor }> {
  const { changes, cursor } = await readLilypadChangesBatch(gate, {
    requests: [{ tableName: options.tableName, since: options.since }],
    changelogTable: options.changelogTable,
  });
  return { changes: changes[0] ?? [], cursor };
}

/**
 * Like {@link readLilypadChanges}, for several tables in one query: `changes[i]` holds the changes
 * of `requests[i]`. Every request shares the cursor for the next read.
 */
export async function readLilypadChangesBatch(
  gate: LilypadDbGate,
  options: { requests: LilypadChangesRequest[]; changelogTable?: string }
): Promise<{ changes: LilypadChange[][]; cursor: LilypadChangelogCursor }> {
  const sql = gate.sql;
  const changelogTable = sql(options.changelogTable ?? LILYPAD_DEFAULT_CHANGELOG_TABLE);
  // Passed as text arrays: an empty xmax selects the lookback of the request, and the running
  // transactions of each cursor are joined by commas
  const tableRefs = options.requests.map((request) => quoteIdentifier(request.tableName));
  const cursors = options.requests.map((request) =>
    'cursor' in request.since ? request.since.cursor : undefined
  );
  const xmaxes = cursors.map((cursor) => cursor?.xmax.toString() ?? '');
  const xips = cursors.map((cursor) => cursor?.xip.join(',') ?? '');
  const lookbacks = options.requests.map((request) =>
    'lookback' in request.since ? String(request.since.lookback / 1000) : '0'
  );

  // One statement, so the snapshot and the rows are read together even through a pooler: the
  // snapshot functions return the snapshot the statement reads with.
  const rows = await sql`
    WITH snapshot AS (
      SELECT pg_snapshot_xmax(current.s)::text AS next_xmax,
        (SELECT coalesce(string_agg(x::text, ','), '') FROM pg_snapshot_xip(current.s) AS x) AS next_xip
      FROM (SELECT pg_current_snapshot() AS s) AS current
    ),
    requests AS (
      SELECT (r.ordinality - 1)::int AS request, r.table_ref,
        NULLIF(r.since_xmax, '')::xid8 AS since_xmax,
        string_to_array(NULLIF(r.since_xip, ''), ',')::xid8[] AS since_xip,
        r.lookback_secs::float8 AS lookback_secs
      FROM unnest(
        ${sql.array(tableRefs)}::text[], ${sql.array(xmaxes)}::text[],
        ${sql.array(xips)}::text[], ${sql.array(lookbacks)}::text[]
      ) WITH ORDINALITY AS r(table_ref, since_xmax, since_xip, lookback_secs, ordinality)
    ),
    targets AS (
      SELECT requests.*, n.nspname AS schema_name, t.relname AS rel_name
      FROM requests
      JOIN pg_class t ON t.oid = to_regclass(requests.table_ref)
      JOIN pg_namespace n ON n.oid = t.relnamespace
    )
    SELECT snapshot.next_xmax, snapshot.next_xip, targets.request,
      c.id::text AS id, c.xid::text AS xid, c.row_id, c.op
    FROM snapshot
    LEFT JOIN targets ON true
    LEFT JOIN LATERAL (
      SELECT c.id, c.xid, c.row_id, c.op FROM ${changelogTable} c
      WHERE targets.since_xmax IS NOT NULL
        AND c.table_name = targets.rel_name
        AND (c.table_schema = targets.schema_name OR c.table_schema IS NULL)
        AND (c.xid >= targets.since_xmax OR c.xid = ANY(targets.since_xip))
      UNION ALL
      SELECT c.id, c.xid, c.row_id, c.op FROM ${changelogTable} c
      WHERE targets.since_xmax IS NULL
        AND c.table_name = targets.rel_name
        AND (c.table_schema = targets.schema_name OR c.table_schema IS NULL)
        AND c.changed_at >= clock_timestamp() - make_interval(secs => targets.lookback_secs)
    ) c ON true
    ORDER BY c.id
  `;

  const changes: LilypadChange[][] = options.requests.map(() => []);
  for (const row of rows) {
    if (row.id !== null) {
      changes[row.request as number]?.push({
        id: row.id as string,
        xid: BigInt(row.xid as string),
        rowId: row.row_id as string | null,
        op: row.op as LilypadChange['op'],
      } as LilypadChange);
    }
  }
  const nextXmax: unknown = rows[0]?.next_xmax;
  const nextXip: unknown = rows[0]?.next_xip;
  if (typeof nextXmax !== 'string' || typeof nextXip !== 'string') {
    throw new Error('Reading the changelog returned no snapshot.');
  }
  const cursor: LilypadChangelogCursor = {
    xmax: BigInt(nextXmax),
    xip: nextXip === '' ? [] : nextXip.split(',').map((xid) => BigInt(xid)),
  };
  return { changes, cursor };
}

/**
 * Deletes the changelog rows older than `olderThan` milliseconds. Call it periodically (e.g. from
 * a scheduled job): `olderThan` must be much larger than the `maxGap` and the `lookback` of the
 * caches.
 *
 * @returns The number of deleted rows.
 */
export async function pruneLilypadChangelog(
  gate: LilypadDbGate,
  options: { olderThan: number; changelogTable?: string }
): Promise<number> {
  const changelogTable = options.changelogTable ?? LILYPAD_DEFAULT_CHANGELOG_TABLE;
  const result = await gate.sql`
    DELETE FROM ${gate.sql(changelogTable)}
    WHERE changed_at < clock_timestamp() - make_interval(secs => ${options.olderThan / 1000})
  `;
  return result.count;
}
