import { describe, it, expect, beforeAll, afterAll, beforeEach, vi } from 'vitest';
import { PostgreSqlContainer, type StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import postgres from 'postgres';
import { LilypadDbGate, type LilypadDbSchema } from './LilypadDbGate';
import LilypadDbCache from '@/cache/LilypadDbCache';
import {
  lilypadChangelogSql,
  lilypadChangelogTriggerSql,
  pruneLilypadChangelog,
  readLilypadChanges,
} from './LilypadChangelog';
import type { LilypadLoggerType } from '@/logger/LilypadLogger';

type User = { id: number; name: string; role: string };

const usersSchema: LilypadDbSchema<User, 'id'> = {
  tableName: 'users',
  primaryKey: 'id',
  primaryKeyShouldAutoDetermine: true,
  cols: { id: { type: 'number' }, name: { type: 'string' }, role: { type: 'string' } },
};

const createMockLogger = () =>
  ({
    error: vi.fn(),
    warn: vi.fn(),
    info: vi.fn(),
    debug: vi.fn(),
  }) as unknown as LilypadLoggerType<'error' | 'warn' | 'info' | 'debug'>;

describe('LilypadDbGate (integration)', () => {
  let container: StartedPostgreSqlContainer;
  let admin: postgres.Sql;
  let gate: LilypadDbGate;

  beforeAll(async () => {
    container = await new PostgreSqlContainer('postgres:16-alpine').start();
    admin = postgres(container.getConnectionUri(), { onnotice: () => {} });
    await admin`
      CREATE TABLE users (
        id serial PRIMARY KEY,
        name text NOT NULL,
        role text NOT NULL DEFAULT 'user',
        is_admin boolean NOT NULL DEFAULT false
      )
    `;
    // The notification contract expected by LilypadDbCache's default listener
    await admin`
      CREATE FUNCTION notify_cache_events() RETURNS trigger AS $$
      BEGIN
        PERFORM pg_notify('cache_events', json_build_object(
          'table', TG_TABLE_NAME,
          'id', COALESCE(NEW.id, OLD.id),
          'op', TG_OP
        )::text);
        RETURN NULL;
      END;
      $$ LANGUAGE plpgsql
    `;
    await admin`
      CREATE TRIGGER users_cache_events AFTER INSERT OR UPDATE OR DELETE ON users
      FOR EACH ROW EXECUTE FUNCTION notify_cache_events()
    `;
    await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
    await admin.unsafe(lilypadChangelogTriggerSql({ table: 'users', primaryKey: 'id' }));
    gate = await LilypadDbGate.create({
      connectionString: container.getConnectionUri(),
      listen: [],
    });
  });

  afterAll(async () => {
    await gate?.close();
    await admin?.end();
    await container?.stop();
  });

  beforeEach(async () => {
    await admin`TRUNCATE users, lilypad_cache_changes RESTART IDENTITY`;
  });

  describe('CRUD', () => {
    it('should insert a row and return it with the generated primary key', async () => {
      const created = await gate.insertToTable(usersSchema, { name: 'Ada', role: 'dev' } as User);

      expect(created).toEqual({ id: 1, name: 'Ada', role: 'dev' });
    });

    it('should ignore the primary key of the data when it is generated by the database', async () => {
      const created = await gate.insertToTable(usersSchema, { id: 999, name: 'Ada', role: 'dev' });

      expect(created?.id).toBe(1);
    });

    it('should require the primary key when it is not generated by the database', async () => {
      const schema = { ...usersSchema, primaryKeyShouldAutoDetermine: false };

      await expect(
        gate.insertToTable(schema, { name: 'Ada', role: 'dev' } as User)
      ).rejects.toThrow('Primary key "id" is missing in the insert data for table "users".');
    });

    it('should never write properties that are not schema columns', async () => {
      const payload = { name: 'Mallory', role: 'user', is_admin: true } as unknown as User;

      await gate.insertToTable(usersSchema, payload);
      await gate.updateToTable(usersSchema, { ...payload, id: 1 });

      const [row] = await admin`SELECT is_admin FROM users WHERE id = 1`;
      expect(row.is_admin).toBe(false);
    });

    it('should select only the schema columns', async () => {
      await admin`INSERT INTO users (name, role, is_admin) VALUES ('Ada', 'dev', true)`;

      expect(await gate.selectAllFromTable(usersSchema)).toEqual([
        { id: 1, name: 'Ada', role: 'dev' },
      ]);
      expect(await gate.selectFromTableByPrimaryKey(usersSchema, 1)).toEqual({
        id: 1,
        name: 'Ada',
        role: 'dev',
      });
      expect(await gate.selectFromTableByPrimaryKey(usersSchema, 2)).toBeNull();
    });

    it('should pass the whole row to the selectSanitizationFn', async () => {
      await admin`INSERT INTO users (name, role, is_admin) VALUES ('Ada', 'dev', true)`;
      const selectSanitizationFn = vi.fn((row: unknown) => row as User);

      await gate.selectAllFromTable({ ...usersSchema, selectSanitizationFn });

      expect(selectSanitizationFn).toHaveBeenCalledWith(
        expect.objectContaining({ is_admin: true })
      );
    });

    it('should update a row and return it', async () => {
      await gate.insertToTable(usersSchema, { name: 'Ada', role: 'dev' } as User);

      const updated = await gate.updateToTable(usersSchema, { id: 1, name: 'Ada', role: 'admin' });

      expect(updated).toEqual({ id: 1, name: 'Ada', role: 'admin' });
    });

    it('should throw when updating a row that does not exist', async () => {
      await expect(
        gate.updateToTable(usersSchema, { id: 42, name: 'Ghost', role: 'user' })
      ).rejects.toThrow('No row with primary key "42" found in table "users".');
    });

    it('should require the primary key to update, even when it is generated', async () => {
      await expect(
        gate.updateToTable(usersSchema, { name: 'Ada', role: 'dev' } as User)
      ).rejects.toThrow('Primary key "id" is missing in the update data for table "users".');
    });

    it('should delete a row', async () => {
      await gate.insertToTable(usersSchema, { name: 'Ada', role: 'dev' } as User);

      await gate.deleteFromTable(usersSchema, 1);

      expect(await gate.selectAllFromTable(usersSchema)).toEqual([]);
    });

    it('should write the result of the insertSanitizationFn, which can remove properties', async () => {
      const schema: LilypadDbSchema<User, 'id'> = {
        ...usersSchema,
        insertSanitizationFn: ({ role: _role, ...rest }) => rest,
      };

      const created = await gate.insertToTable(schema, { name: 'Mallory', role: 'admin' });

      expect(created?.role).toBe('user');
    });

    it('should skip undefined values instead of failing', async () => {
      // e.g. an optional field of a request body that was not sent
      const data = { name: 'Ada', role: undefined as unknown as string };

      const created = await gate.insertToTable(usersSchema, data);

      expect(created).toEqual({ id: 1, name: 'Ada', role: 'user' });
    });

    it('should update only the columns present in the data', async () => {
      await gate.insertToTable(usersSchema, { name: 'Ada', role: 'dev' });

      const updated = await gate.updateToTable(usersSchema, { id: 1, role: 'admin' });

      expect(updated).toEqual({ id: 1, name: 'Ada', role: 'admin' });
    });

    it('should select tables larger than one cursor batch', async () => {
      await admin`INSERT INTO users (name) SELECT 'user' || i FROM generate_series(1, 2500) AS i`;

      expect(await gate.selectAllFromTable(usersSchema)).toHaveLength(2500);
    });

    it('should cancel queries longer than statementTimeout on the server', async () => {
      const limitedGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        statementTimeout: 100,
      });

      await expect(limitedGate.sql`SELECT pg_sleep(1)`).rejects.toThrow('statement timeout');
      await limitedGate.close();
    });

    it('should escape table names', async () => {
      const schema = { ...usersSchema, tableName: 'users; DROP TABLE users; --' };

      await expect(gate.selectAllFromTable(schema)).rejects.toThrow('does not exist');
      const [{ exists }] = await admin`SELECT to_regclass('users') IS NOT NULL AS exists`;
      expect(exists).toBe(true);
    });
  });

  describe('listeners', () => {
    it('should deliver notifications to every callback of the channel', async () => {
      const first = vi.fn();
      const second = vi.fn();
      await gate.addListener({ channel: 'test_channel', callbackId: 'first', callback: first });
      await gate.addListener({ channel: 'test_channel', callbackId: 'second', callback: second });

      await admin.notify('test_channel', 'hello');

      await vi.waitFor(() => {
        expect(first).toHaveBeenCalledWith('hello');
        expect(second).toHaveBeenCalledWith('hello');
      });
      await gate.removeListener('test_channel', 'first');
      await gate.removeListener('test_channel', 'second');
    });

    it('should log a rejected async callback without affecting the others', async () => {
      const logger = createMockLogger();
      const loggedGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        logger,
        listen: [
          {
            channel: 'failing_channel',
            callbackId: 'failing',
            callback: async () => {
              throw new Error('callback failed');
            },
          },
        ],
      });
      const healthy = vi.fn();
      await loggedGate.addListener({
        channel: 'failing_channel',
        callbackId: 'healthy',
        callback: healthy,
      });

      await admin.notify('failing_channel', 'payload');

      await vi.waitFor(() => {
        expect(healthy).toHaveBeenCalledWith('payload');
        expect(logger.error).toHaveBeenCalledWith(
          loggedGate.id,
          expect.stringContaining('"failing"'),
          expect.any(Error)
        );
      });
      await loggedGate.close();
    });

    it('should stop delivering notifications to removed callbacks', async () => {
      const removed = vi.fn();
      const kept = vi.fn();
      await gate.addListener({
        channel: 'removal_channel',
        callbackId: 'removed',
        callback: removed,
      });
      await gate.addListener({ channel: 'removal_channel', callbackId: 'kept', callback: kept });

      expect(await gate.removeListener('removal_channel', 'removed')).toBe(true);
      await admin.notify('removal_channel', 'payload');

      await vi.waitFor(() => expect(kept).toHaveBeenCalled());
      expect(removed).not.toHaveBeenCalled();
      await gate.removeListener('removal_channel', 'kept');
    });

    it('should share a single LISTEN between concurrent addListener calls', async () => {
      const first = vi.fn();
      const second = vi.fn();

      await Promise.all([
        gate.addListener({ channel: 'concurrent_channel', callbackId: 'first', callback: first }),
        gate.addListener({ channel: 'concurrent_channel', callbackId: 'second', callback: second }),
      ]);
      await admin.notify('concurrent_channel', 'payload');

      await vi.waitFor(() => {
        expect(first).toHaveBeenCalledOnce();
        expect(second).toHaveBeenCalledOnce();
      });
      await gate.removeListener('concurrent_channel', 'first');
      await gate.removeListener('concurrent_channel', 'second');
    });
  });

  describe('listener lifecycle', () => {
    it('should call onReconnect once the listener connection is re-established', async () => {
      const callback = vi.fn();
      const onReconnect = vi.fn();
      const reconnectingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listen: [{ channel: 'reconnect_channel', callbackId: 'cb', callback, onReconnect }],
      });
      expect(onReconnect).not.toHaveBeenCalled();

      await admin`
        SELECT pg_terminate_backend(pid) FROM pg_stat_activity
        WHERE query ILIKE 'listen%reconnect_channel%'
      `;

      await vi.waitFor(() => expect(onReconnect).toHaveBeenCalledOnce(), { timeout: 10000 });
      await admin.notify('reconnect_channel', 'after');
      await vi.waitFor(() => expect(callback).toHaveBeenCalledWith('after'));
      await reconnectingGate.close();
    });

    it('should remove a callback whose LISTEN is still pending', async () => {
      const callback = vi.fn();
      const adding = gate.addListener({ channel: 'pending_channel', callbackId: 'cb', callback });

      expect(await gate.removeListener('pending_channel', 'cb')).toBe(true);
      await adding;
      await admin.notify('pending_channel', 'payload');
      await new Promise((resolve) => setTimeout(resolve, 200));

      expect(callback).not.toHaveBeenCalled();
    });

    it('should close a gate that still has active listeners', async () => {
      const closingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listen: [{ channel: 'closing_channel', callbackId: 'cb', callback: vi.fn() }],
      });

      await expect(closingGate.close()).resolves.toBeUndefined();
    });
  });

  describe('changelog', () => {
    const readAll = () =>
      readLilypadChanges(gate, { tableName: 'users', since: { lookback: 60_000 } });

    it('should record inserts, updates, deletes and primary key changes', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      await admin`UPDATE users SET role = 'admin' WHERE id = 1`;
      await admin`UPDATE users SET id = 2 WHERE id = 1`;
      await admin`DELETE FROM users WHERE id = 2`;

      const { changes } = await readAll();

      expect(changes.map(({ op, rowId }) => `${op}:${rowId}`)).toEqual([
        'INSERT:1',
        'UPDATE:1',
        'DELETE:1', // the primary key change removes the old key...
        'UPDATE:2', // ...and updates the new one
        'DELETE:2',
      ]);
    });

    it('should not miss a transaction that commits after a later one', async () => {
      const slow = await admin.reserve();
      try {
        await slow`BEGIN`;
        await slow`INSERT INTO users (name) VALUES ('slow')`; // id 1, not committed yet
        await admin`INSERT INTO users (name) VALUES ('fast')`; // id 2, committed
        const first = await readAll();
        expect(first.changes.map((change) => change.rowId)).toEqual(['2']);

        await slow`COMMIT`;
        const next = await readLilypadChanges(gate, {
          tableName: 'users',
          since: { cursor: first.cursor },
        });

        expect(next.changes.map((change) => change.rowId)).toContain('1');
      } finally {
        slow.release();
      }
    });

    it('should delete the rows older than the retention', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;

      expect(await pruneLilypadChangelog(gate, { olderThan: 0 })).toBe(1);
      expect((await readAll()).changes).toEqual([]);
    });

    it('should keep a LilypadDbCache in sync without LISTEN', async () => {
      const cache = await LilypadDbCache.create<number, User, 'id'>(60_000, {
        dbGate: { gate, schema: usersSchema },
        sync: { strategy: 'changelog', pollInterval: 0 },
      });
      await cache.sqlCreate({ name: 'Ada', role: 'dev' });
      expect(await cache.getOrFetch(1)).toMatchObject({ role: 'dev' });

      await admin`UPDATE users SET role = 'admin' WHERE id = 1`;
      expect(await cache.getOrFetch(1)).toMatchObject({ role: 'admin' });

      await admin`INSERT INTO users (name) VALUES ('Grace')`;
      expect((await cache.getAll()).map((user) => user.name).sort()).toEqual(['Ada', 'Grace']);

      await admin`DELETE FROM users WHERE id = 1`;
      expect(await cache.getOrFetch(1)).toBeNull();
      await cache.dispose();
    });

    it('should let LISTEN and the changelog work together', async () => {
      const listened = vi.fn();
      await gate.addListener({ channel: 'cache_events', callbackId: 'both', callback: listened });

      await admin`INSERT INTO users (name) VALUES ('Ada')`;

      await vi.waitFor(() => expect(listened).toHaveBeenCalled());
      expect((await readAll()).changes).toHaveLength(1);
      await gate.removeListener('cache_events', 'both');
    });
  });

  describe('singleton', () => {
    it('should create a new instance after the singleton is closed', async () => {
      const options = {
        connectionString: container.getConnectionUri(),
        listen: [],
        singleton: true as const,
        singletonIdentifier: 'LilypadDbGate.integration-singleton',
      };
      const first = await LilypadDbGate.create(options);

      expect(await LilypadDbGate.create(options)).toBe(first);

      await first.close();
      const second = await LilypadDbGate.create(options);

      expect(second).not.toBe(first);
      await second.close();
    });
  });

  describe('with LilypadDbCache', () => {
    it('should keep the cache in sync through cache_events notifications', async () => {
      const cache = await LilypadDbCache.create<number, User, 'id'>(60000, {
        dbGate: { gate, schema: usersSchema },
      });
      const created = await cache.sqlCreate({ name: 'Ada', role: 'dev' });
      expect(created?.id).toBe(1);

      await admin`UPDATE users SET role = 'admin' WHERE id = 1`;
      await vi.waitFor(() => expect(cache.get(1)).toEqual({ id: 1, name: 'Ada', role: 'admin' }));
      expect([...cache.bulkGet({}).keys()]).toEqual([1]);

      await admin`DELETE FROM users WHERE id = 1`;
      await vi.waitFor(() => expect(cache.get(1)).toBeNull());

      await cache.dispose();
    });
  });
});
