import {
  LILYPAD_DEFAULT_CHANGELOG_TABLE,
  LILYPAD_DEFAULT_NOTIFY_CHANNEL,
  LILYPAD_RESERVED_CHANNEL_PART,
} from '@/dbConfig/LilypadDbConfigDefaults';
import type { LilypadDbGate } from '@/dbGate/LilypadDbGate';
import { assertNumberOption } from '@/internal/LilypadValidation';

/**
 * The changelog records every change of the cached tables in a table, so that each instance can
 * read the changes made since its last check with one query. It needs no long-lived connection
 * (unlike `LISTEN/NOTIFY`), so it suits serverless platforms, and it also catches the changes made
 * by other programs. It needs PostgreSQL 16 or later, the oldest version the library supports.
 */

/**
 * The version of the changelog table and trigger function generated by {@link lilypadChangelogSql}.
 * The function carries it in its comment (`lilypad-changelog:<version>`), so that
 * `checkLilypadSchema` can tell an installation made by an older version of the library.
 */
export const LILYPAD_CHANGELOG_VERSION = 10;
export const LILYPAD_CHANGELOG_VERSION_PREFIX = 'lilypad-changelog:';

/**
 * PostgreSQL's `FirstNormalObjectId`: types, functions and casts whose OID is below it are built-in
 * (assigned by `initdb`); the rest are user-defined. Only a superuser can attach a cast to, or an
 * I/O function of, a built-in type, so a built-in type is trusted.
 */
const LILYPAD_FIRST_NORMAL_OBJECT_ID = 16384;

/** The deepest chain of domains/arrays the key-type check walks; beyond it, the key is refused. */
const KEY_TYPE_MAX_DEPTH = 32;

/**
 * A SQL boolean expression that is true only when the type `startOid` is safe to convert with
 * `to_jsonb` while running as the changelog owner. `to_jsonb` of a non-built-in value runs its cast
 * to `json` if one exists, else its output function, and recurses into the elements of an array and
 * the fields of a composite; a cast or I/O function a role owns runs that role's code. So a type is
 * safe only when every node it is built from (resolving domains to their base and arrays to their
 * element) is either built-in (OID below {@link LILYPAD_FIRST_NORMAL_OBJECT_ID}), or a base or enum
 * type whose type, output function and every `json`/`jsonb` cast function are owned by a superuser
 * (or built in). A user-defined (non-built-in) composite, range or multirange type, or a chain
 * deeper than {@link KEY_TYPE_MAX_DEPTH}, is refused (built-in ones, such as `int4range`, pass). It fails closed: an empty walk is unsafe. The same fragment guards the trigger and the
 * schema check, so they cannot drift. It reads only `pg_catalog`; `startOid` must be trusted SQL.
 */
export function lilypadSafeKeyTypeSql(startOid: string): string {
  const fno = LILYPAD_FIRST_NORMAL_OBJECT_ID;
  return `coalesce((
    WITH RECURSIVE walk(oid, typtype, typbasetype, typelem, typowner, typoutput, depth) AS (
      SELECT ty.oid, ty.typtype, ty.typbasetype, ty.typelem, ty.typowner, ty.typoutput, 0
      FROM pg_catalog.pg_type ty WHERE ty.oid = ${startOid}
      UNION ALL
      SELECT nt.oid, nt.typtype, nt.typbasetype, nt.typelem, nt.typowner, nt.typoutput, walk.depth + 1
      FROM walk JOIN pg_catalog.pg_type nt ON nt.oid = CASE
        WHEN walk.typtype = 'd' THEN walk.typbasetype
        WHEN walk.typelem <> 0 THEN walk.typelem
        ELSE NULL END
      WHERE walk.depth < ${KEY_TYPE_MAX_DEPTH}
    )
    SELECT bool_and(
      -- A domain or a registered array type is passed through (resolved above), not checked itself
      CASE WHEN node.typtype = 'd'
            OR (node.typelem <> 0 AND EXISTS (
                 SELECT 1 FROM pg_catalog.pg_type e
                 WHERE e.oid = node.typelem AND e.typarray = node.oid))
        THEN true
        ELSE node.oid < ${fno}
          OR (
            node.typtype IN ('b', 'e')
            AND coalesce(town.rolsuper, false)
            AND (node.typoutput < ${fno} OR coalesce(oown.rolsuper, false))
            AND NOT EXISTS (
              SELECT 1 FROM pg_catalog.pg_cast cs
              JOIN pg_catalog.pg_proc cp ON cp.oid = cs.castfunc
              JOIN pg_catalog.pg_roles cr ON cr.oid = cp.proowner
              WHERE cs.castsource = node.oid
                AND cs.casttarget IN ('pg_catalog.json'::regtype, 'pg_catalog.jsonb'::regtype)
                AND cs.castfunc >= ${fno} AND NOT cr.rolsuper
            )
          )
      END
    ) AND max(node.depth) < ${KEY_TYPE_MAX_DEPTH}
    FROM walk AS node
    LEFT JOIN pg_catalog.pg_roles town ON town.oid = node.typowner
    LEFT JOIN pg_catalog.pg_proc op ON op.oid = node.typoutput
    LEFT JOIN pg_catalog.pg_roles oown ON oown.oid = op.proowner
  ), false)`;
}
/** Above this number of rows changed by one statement, the trigger sends one `BULK` notification. */
export const LILYPAD_DEFAULT_NOTIFY_BULK_THRESHOLD = 1000;

/**
 * The shortest retention that {@link pruneLilypadChangelog} accepts without `force`: the default
 * `maxGap` of the caches. A shorter one deletes rows that the caches may still have to read.
 */
export const LILYPAD_MIN_CHANGELOG_RETENTION: number = 60 * 60 * 1000;

/** The transition tables of the statement triggers (version 4): the rows before and after. */
export const LILYPAD_CHANGELOG_OLD_ROWS = 'lilypad_old';
export const LILYPAD_CHANGELOG_NEW_ROWS = 'lilypad_new';

/** Replaces the characters that are not allowed in the names derived from a table name. */
function identifierPrefix(name: string): string {
  return name.replace(/\W/g, '_');
}

/** PostgreSQL truncates longer identifiers (`NAMEDATALEN - 1`). */
const MAX_IDENTIFIER_BYTES = 63;

const encoder = new TextEncoder();

/**
 * Checks a notification channel: `pg_notify` rejects an empty name and a name longer than
 * {@link MAX_IDENTIFIER_BYTES} bytes (a trigger that notifies on it would fail every write), and
 * `LISTEN` truncates a longer one (its notifications would never be delivered).
 *
 * @throws If the channel is not a non-empty string of at most 63 bytes.
 */
export function assertLilypadChannel(owner: string, channel: unknown): void {
  if (typeof channel !== 'string' || channel === '') {
    throw new Error(
      `${owner}: the channel must be a non-empty string (got ${JSON.stringify(channel)}).`
    );
  }
  if (encoder.encode(channel).length > MAX_IDENTIFIER_BYTES) {
    throw new Error(
      `${owner}: the channel "${channel}" is longer than ${MAX_IDENTIFIER_BYTES} bytes, which PostgreSQL rejects or truncates.`
    );
  }
}

/**
 * A name derived from a table name, at most {@link MAX_IDENTIFIER_BYTES} long: a longer prefix is
 * cut and followed by a hash of the whole prefix, so that the suffixes stay distinct instead of
 * being truncated away (the prefix is ASCII: one byte per character).
 */
function derivedName(prefix: string, suffix: string): string {
  if (prefix.length + suffix.length <= MAX_IDENTIFIER_BYTES) {
    return prefix + suffix;
  }
  // FNV-1a, 32 bits
  let hash = 0x811c9dc5;
  for (let index = 0; index < prefix.length; index++) {
    hash = Math.imul(hash ^ prefix.charCodeAt(index), 0x01000193);
  }
  const tag = (hash >>> 0).toString(16).padStart(8, '0');
  return `${prefix.slice(0, MAX_IDENTIFIER_BYTES - suffix.length - tag.length - 1)}_${tag}${suffix}`;
}

/**
 * A name derived from the name of the changelog table (its functions and indexes). Their suffixes
 * differ from their second character, so the names that PostgreSQL truncates stay distinct while
 * the prefix is shorter than 62 bytes: they are kept as they are, as earlier versions installed
 * them. From 62 bytes, PostgreSQL would truncate two of them into one: they are cut with a hash
 * instead ({@link derivedName}).
 */
function changelogObjectName(prefix: string, suffix: string): string {
  return prefix.length < MAX_IDENTIFIER_BYTES - 1 ? prefix + suffix : derivedName(prefix, suffix);
}

/**
 * Dollar-quotes a body with a tag that it does not contain: the names of a config may contain `$`.
 * The tag is lengthened with `_` until it is unique.
 */
export function dollarQuote(body: string, tag = ''): string {
  let delimiter = `$${tag}$`;
  // Also when the end of the body and the delimiter form one (`...$` followed by `$$`)
  while (`${body}${delimiter}`.indexOf(delimiter) !== body.length) {
    tag += '_';
    delimiter = `$${tag}$`;
  }
  return `${delimiter}${body}${delimiter}`;
}

/** Quotes an identifier; `schema.table` is quoted part by part. */
export function quoteIdentifier(identifier: string): string {
  return identifier
    .split('.')
    .map((part) => `"${part.replace(/"/g, '""')}"`)
    .join('.');
}

/** Quotes a string literal (with `standard_conforming_strings`, on since PostgreSQL 9.1). */
export function quoteLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** The trigger function name for a changelog table. */
export function triggerFunctionName(changelogTable: string): string {
  return changelogObjectName(identifierPrefix(changelogTable), '_record');
}

/** The name of the function that deletes the old rows of a changelog table (`prune` option). */
export function pruneFunctionName(changelogTable: string): string {
  return changelogObjectName(identifierPrefix(changelogTable), '_prune');
}

const TRIGGER_SUFFIXES = {
  insert: '_lilypad_insert',
  update: '_lilypad_update',
  delete: '_lilypad_delete',
  truncate: '_lilypad_truncate',
  legacyRow: '_lilypad_changes',
} as const;

/**
 * The names of the triggers that record the changes of a table: one statement trigger per event,
 * and the row trigger that versions 3 and earlier installed instead of the first three (which
 * `lilypadChangelogTriggerSql` drops).
 *
 * With `unshortened`, the names of versions 5 and earlier: PostgreSQL truncated the long ones (so
 * that the four statement triggers of a long table name were one), and truncates them the same way
 * in a `DROP TRIGGER`.
 */
function changelogTriggerNames(
  table: string,
  unshortened = false
): Record<keyof typeof TRIGGER_SUFFIXES, string> {
  const prefix = identifierPrefix(table);
  const name = (suffix: string) => (unshortened ? prefix + suffix : derivedName(prefix, suffix));
  return {
    insert: name(TRIGGER_SUFFIXES.insert),
    update: name(TRIGGER_SUFFIXES.update),
    delete: name(TRIGGER_SUFFIXES.delete),
    truncate: name(TRIGGER_SUFFIXES.truncate),
    legacyRow: name(TRIGGER_SUFFIXES.legacyRow),
  };
}

/** Escapes a string placed in the format string of the SQL `format()` function. */
function escapeFormat(value: string): string {
  return value.replace(/%/g, '%%');
}

export type LilypadChangelogSqlOptions = {
  /**
   * Name of the changelog table (`table` or `schema.table`), as in the other changelog helpers.
   * Defaults to `lilypad_cache_changes`.
   */
  changelogTable?: string | undefined;
  /**
   * Channel on which the trigger also sends a `NOTIFY` for the `listen` strategy, or `false` to
   * send none. Defaults to `cache_events`.
   */
  notifyChannel?: string | false | undefined;
  /**
   * With a `notifyChannel`, a statement that changes more rows than this sends one `BULK`
   * notification instead of one per row: the caches then expire every entry of the table instead
   * of re-reading each row, and the `NOTIFY` queue is not flooded. Defaults to 1000.
   */
  notifyBulkThreshold?: number | undefined;
  /**
   * Makes the trigger delete the old changelog rows itself, so that no scheduled job is needed:
   * on about one statement in `every`, it deletes up to `batchSize` rows older than `olderThan`,
   * in the writing transaction. `false` (the default) leaves the pruning to
   * {@link pruneLilypadChangelog} or {@link lilypadChangelogPruneScheduleSql}.
   */
  prune?: LilypadChangelogPruneOptions | false | undefined;
};

export type LilypadChangelogPruneOptions = {
  /**
   * The retention, in milliseconds: the rows older than this are deleted. It must be much longer
   * than the `maxGap` and the `lookback` of the caches, and than the longest transaction (e.g. 24 h).
   */
  olderThan: number;
  /**
   * The trigger prunes on about one call in `every` (one call per statement). Defaults to 20.
   * `batchSize / every` is the average number of rows pruned per statement: it must stay above the
   * average number of rows a statement records, or the table keeps growing.
   */
  every?: number | undefined;
  /** The most rows one prune deletes. Defaults to 1000. */
  batchSize?: number | undefined;
  /**
   * Accepts an `olderThan` below one hour ({@link LILYPAD_MIN_CHANGELOG_RETENTION}), which
   * otherwise throws: it deletes rows that the caches may still have to read.
   */
  force?: boolean | undefined;
};

/**
 * The placeholders of the body of the trigger function: the changelog table (as an identifier, and
 * as a literal) and the prune function, which the `DO` block that creates it qualifies (see
 * `recordDoBody`).
 */
const CHANGELOG_TOKEN = '__lilypad_changelog__';
const CHANGELOG_LITERAL_TOKEN = '__lilypad_changelog_literal__';
const PRUNE_TOKEN = '__lilypad_prune__';

/** The comment of the trigger function that records its prune options (read back by the schema check). */
const PRUNE_MARKER = 'lilypad-prune:';

type ResolvedPruneOptions = Required<Omit<LilypadChangelogPruneOptions, 'force'>>;

/**
 * Throws for a retention below one hour without `force`: it is in milliseconds, and a retention
 * given in seconds by mistake would delete rows that the caches still have to read.
 */
function assertRetention(
  owner: string,
  name: string,
  olderThan: number,
  force: boolean | undefined
): void {
  if (olderThan < LILYPAD_MIN_CHANGELOG_RETENTION && force !== true) {
    throw new Error(
      `${owner}: ${name} is ${olderThan} ms, less than one hour: the caches may still need these rows (it is in milliseconds). Pass force: true to prune them anyway.`
    );
  }
}

function resolvePruneOptions(
  owner: string,
  prune: LilypadChangelogPruneOptions | false | undefined
): ResolvedPruneOptions | undefined {
  if (!prune) {
    return undefined;
  }
  assertNumberOption(owner, 'prune.olderThan', prune.olderThan, 'positive');
  assertNumberOption(owner, 'prune.every', prune.every, 'positive-integer');
  assertNumberOption(owner, 'prune.batchSize', prune.batchSize, 'positive-integer');
  assertRetention(owner, 'prune.olderThan', prune.olderThan, prune.force);
  return {
    olderThan: prune.olderThan,
    every: prune.every ?? 20,
    batchSize: prune.batchSize ?? 1000,
  };
}

/**
 * The `prune` options of an installed trigger function, from its source, or `false` if it does not
 * prune: the SQL that fixes an outdated changelog keeps them.
 */
export function installedLilypadChangelogPrune(
  source: string | null
): LilypadChangelogPruneOptions | false {
  const match = source
    ? new RegExp(`${PRUNE_MARKER} olderThan=(\\S+) every=(\\d+) batchSize=(\\d+)`).exec(source)
    : null;
  if (!match) {
    return false;
  }
  const prune = {
    olderThan: Number(match[1]),
    every: Number(match[2]),
    batchSize: Number(match[3]),
  };
  return Number.isFinite(prune.olderThan) &&
    prune.olderThan > 0 &&
    prune.every > 0 &&
    prune.batchSize > 0
    ? prune
    : false;
}

/** The SQL condition on `changed_at` of the rows older than `olderThan` milliseconds. */
export function olderThanCondition(olderThan: number): string {
  return `changed_at < clock_timestamp() - make_interval(secs => ${olderThan / 1000})`;
}

/**
 * The body of the `DO` block that creates the prune function: `format()` puts the changelog table,
 * qualified with its schema, in the function, whose body is then passed as a literal (`%L`): the
 * schema, known only there, may contain `$`.
 */
function pruneDoBody(
  pruneFunction: string,
  quotedTable: string,
  prune: ResolvedPruneOptions
): string {
  const functionBody = `
  DELETE FROM %1$s WHERE id IN (
    SELECT id FROM %1$s
    WHERE ${escapeFormat(olderThanCondition(prune.olderThan))}
    ORDER BY changed_at
    LIMIT ${prune.batchSize}
    FOR UPDATE SKIP LOCKED
  );
`;
  return dollarQuote(
    `
DECLARE
  changelog text := (
    SELECT format('%I.%I', n.nspname, c.relname)
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = ${quoteLiteral(quotedTable)}::regclass
  );
BEGIN
  EXECUTE format(
    'CREATE OR REPLACE FUNCTION %s() RETURNS void AS %L LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, pg_temp',
    ${quoteLiteral(pruneFunction)}, format(${dollarQuote(functionBody, 'body')}, changelog));
END
`,
    'lilypad'
  );
}

/**
 * The SQL that creates the changelog table and its trigger function. Run it once, in a migration.
 * It is idempotent (`IF NOT EXISTS` / `CREATE OR REPLACE`).
 *
 * Then attach the trigger to every cached table with {@link lilypadChangelogTriggerSql}.
 */
export function lilypadChangelogSql(options: LilypadChangelogSqlOptions = {}): string {
  if (Object.hasOwn(options, 'table')) {
    // The option of versions 0.7 and earlier: `table` is the cached table in the other helpers
    throw new Error(
      'lilypadChangelogSql: the `table` option is now `changelogTable` (the name of the changelog table).'
    );
  }
  const table = options.changelogTable ?? LILYPAD_DEFAULT_CHANGELOG_TABLE;
  const channel = options.notifyChannel ?? LILYPAD_DEFAULT_NOTIFY_CHANNEL;
  if (channel !== false) {
    assertLilypadChannel('lilypadChangelogSql', channel);
    if (channel.includes(LILYPAD_RESERVED_CHANNEL_PART)) {
      // It would be taken for a placeholder of the trigger function
      throw new Error(
        `lilypadChangelogSql: the notifyChannel "${channel}" contains "${LILYPAD_RESERVED_CHANNEL_PART}".`
      );
    }
  }
  const prune = resolvePruneOptions('lilypadChangelogSql', options.prune);
  assertNumberOption(
    'lilypadChangelogSql',
    'notifyBulkThreshold',
    options.notifyBulkThreshold,
    'positive-integer'
  );
  const bulkThreshold = options.notifyBulkThreshold ?? LILYPAD_DEFAULT_NOTIFY_BULK_THRESHOLD;
  const quotedTable = quoteIdentifier(table);
  const indexPrefix = identifierPrefix(table);
  const indexName = (suffix: string) => quoteIdentifier(changelogObjectName(indexPrefix, suffix));
  // From a 62-byte prefix, earlier versions created one index, under the name PostgreSQL truncated
  // both to: it is dropped (in the schema of the changelog), the hashed names replace it
  const truncatedIndex = `${indexPrefix}_table_xid_idx`.slice(0, MAX_IDENTIFIER_BYTES);
  const schemaPrefix = table.includes('.')
    ? `${quoteIdentifier(table.slice(0, table.lastIndexOf('.')))}.`
    : '';
  const hashedIndexes = ['_table_xid_idx', '_changed_at_idx'].map((suffix) =>
    changelogObjectName(indexPrefix, suffix)
  );
  // Never one of the hashed indexes (a prefix that would end with the hash and the suffix)
  const dropTruncatedIndex =
    indexPrefix.length < MAX_IDENTIFIER_BYTES - 1 || hashedIndexes.includes(truncatedIndex)
      ? ''
      : `-- The index that versions 7 and earlier created for both, truncated by PostgreSQL
DROP INDEX IF EXISTS ${schemaPrefix}${quoteIdentifier(truncatedIndex)};
`;
  const pruneFunction = quoteIdentifier(pruneFunctionName(table));
  // Before each RETURN of the trigger function. Only in READ COMMITTED: in a stricter isolation,
  // deleting a row that a concurrent prune deleted would fail the write (serialization failure).
  const pruneCall = (indent: string) =>
    prune
      ? `
${indent}IF random() * ${prune.every} < 1 AND current_setting('transaction_isolation') = 'read committed' THEN
${indent}  PERFORM ${PRUNE_TOKEN}();
${indent}END IF;`
      : '';
  const notify = (idExpression: string, opExpression: string) =>
    channel === false
      ? ''
      : `
    PERFORM pg_notify(${quoteLiteral(channel)}, json_build_object(
      'schema', TG_TABLE_SCHEMA, 'table', TG_TABLE_NAME, 'id', ${idExpression}, 'op', ${opExpression},
      'xid', pg_current_xact_id()::text
    )::text);`;
  const functionName = quoteIdentifier(triggerFunctionName(table));
  const oldRows = LILYPAD_CHANGELOG_OLD_ROWS;
  const newRows = LILYPAD_CHANGELOG_NEW_ROWS;
  // The notifications of a statement trigger: one per row, or one BULK notification above the
  // threshold (the caches then expire the whole table). $1 and $2 are the schema and the name of
  // the table, %s the query of the changed rows
  const notifyChanged =
    channel === false
      ? ''
      : `
  GET DIAGNOSTICS recorded = ROW_COUNT;
  IF recorded > ${bulkThreshold} THEN
    PERFORM pg_notify(${quoteLiteral(channel)}, json_build_object(
      'schema', TG_TABLE_SCHEMA, 'table', TG_TABLE_NAME, 'op', 'BULK',
      'xid', pg_current_xact_id()::text
    )::text);
  ELSIF recorded > 0 THEN
    EXECUTE format(${dollarQuote(
      `
      SELECT pg_notify(${escapeFormat(quoteLiteral(channel))}, json_build_object(
        'schema', $1, 'table', $2, 'id', changed.row_id, 'op', changed.op,
        'xid', pg_current_xact_id()::text
      )::text) FROM (%s) AS changed
    `,
      'notify'
    )}, changed) USING TG_TABLE_SCHEMA, TG_TABLE_NAME;
  END IF;`;

  return `CREATE TABLE IF NOT EXISTS ${quotedTable} (
  id           bigserial   PRIMARY KEY,
  xid          xid8        NOT NULL DEFAULT pg_current_xact_id(),
  table_schema text,
  table_name   text        NOT NULL,
  row_id       text,
  op           text        NOT NULL,
  changed_at   timestamptz NOT NULL DEFAULT clock_timestamp()
);
-- Version 1 had no schema column: tables of the same name in different schemas were mixed up
ALTER TABLE ${quotedTable} ADD COLUMN IF NOT EXISTS table_schema text;
-- Version 3 records TRUNCATE, which concerns no single row
ALTER TABLE ${quotedTable} ALTER COLUMN row_id DROP NOT NULL;
${dropTruncatedIndex}CREATE INDEX IF NOT EXISTS ${indexName('_table_xid_idx')}
  ON ${quotedTable} (table_name, xid);
CREATE INDEX IF NOT EXISTS ${indexName('_changed_at_idx')}
  ON ${quotedTable} (changed_at);
${
  prune
    ? `
-- Deletes up to ${prune.batchSize} changelog rows older than the retention, for the trigger function.
-- SECURITY DEFINER, so that the writing roles need no DELETE privilege on the changelog. The
-- changelog table is qualified with the schema this migration resolves it to, and pg_temp comes
-- last in the search_path: otherwise it is searched first, and any role could make the function
-- delete from a temporary table of its own, whose triggers would run with the privileges of the
-- owner. SKIP LOCKED: concurrent prunes delete different rows and never wait for each other.
DO ${pruneDoBody(pruneFunction, quotedTable, prune)};
`
    : ''
}
-- Records the changes of the rows of a statement, or a TRUNCATE of the table; the trigger argument
-- is the primary key column. It runs as its owner, so that only the triggers write the changelog:
-- the writing roles need no privilege on it, and cannot record changes of their own (every cache
-- trusts the changelog). So its search_path is pg_catalog then pg_temp only, and the changelog and
-- the prune function are qualified with the schemas this migration resolves them to: a schema
-- writable by others (public) could otherwise hold an object that stands for one of them, or an
-- overload of a built-in function that matches better, run with the privileges of the owner.
DO ${recordDoBody(
    functionName,
    quotedTable,
    prune ? pruneFunction : undefined,
    `
DECLARE
  changed text;
  recorded bigint;
  key_type oid;
BEGIN${
      prune
        ? `
  -- ${PRUNE_MARKER} olderThan=${prune.olderThan} every=${prune.every} batchSize=${prune.batchSize}`
        : ''
    }
  IF TG_OP = 'TRUNCATE' THEN
    INSERT INTO ${CHANGELOG_TOKEN} (table_schema, table_name, row_id, op)
      VALUES (TG_TABLE_SCHEMA, TG_TABLE_NAME, NULL, 'TRUNCATE');${notify('NULL', `'TRUNCATE'`)}${pruneCall('    ')}
    RETURN NULL;
  END IF;

  IF TG_LEVEL = 'ROW' THEN
    -- A row trigger of version 3 or earlier: its changes can no longer be recorded. The write
    -- goes on (a failing write would be worse), and the schema check reports the trigger
    RAISE WARNING 'lilypad: the row trigger % on %.% is outdated, run lilypadChangelogTriggerSql', TG_NAME, TG_TABLE_SCHEMA, TG_TABLE_NAME;
    RETURN NULL;
  END IF;

  -- The transition tables are read below by their unqualified names. A statement trigger created
  -- without them (no REFERENCING, or other names) would make those names resolve to pg_temp: a
  -- temporary table or view of the writing session, which this function would read, and whose
  -- functions it would run, as its owner. Fail closed: refuse unless the firing trigger declares them
  IF NOT EXISTS (
    SELECT 1 FROM pg_catalog.pg_trigger t
    WHERE t.tgrelid = TG_RELID AND t.tgname = TG_NAME
      AND (TG_OP = 'INSERT' OR t.tgoldtable = '${oldRows}')
      AND (TG_OP = 'DELETE' OR t.tgnewtable = '${newRows}')
  ) THEN
    RAISE EXCEPTION 'lilypad: the changelog cannot record %.% because the trigger % does not declare its transition tables (${oldRows}, ${newRows}): reinstall the triggers with lilypadChangelogTriggerSql.', TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_NAME;
  END IF;

  -- The key column is read below with to_jsonb (and compared with it in the UPDATE branch), which
  -- this function runs as its owner. to_jsonb resolves a cast or output function by the value's type,
  -- not by the search_path, so a key of a type whose cast or I/O function a non-superuser owns would
  -- run that role's code as the owner. Fail closed: refuse unless the key column exists and its type
  -- is proven safe (see lilypadSafeKeyTypeSql: a built-in type, or a base/enum type whose type,
  -- output function and json casts are owned by superusers, resolving domains and arrays). TG_ARGV[0]
  -- is cast to the name type, so it is clipped to 63 bytes exactly as the parser clips the %I below.
  SELECT a.atttypid INTO key_type
  FROM pg_catalog.pg_attribute a
  WHERE a.attrelid = TG_RELID AND a.attname = TG_ARGV[0]::pg_catalog.name
    AND a.attnum > 0 AND NOT a.attisdropped;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'lilypad: the changelog cannot record %.% because its primary key column % does not exist (renamed or dropped?): reinstall the triggers with lilypadChangelogTriggerSql.', TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_ARGV[0];
  END IF;
  IF NOT (${lilypadSafeKeyTypeSql('key_type')}) THEN
    RAISE EXCEPTION 'lilypad: the changelog cannot record %.% because its primary key column % has an unsafe type: converting it would run a non-superuser''s code as the changelog owner. Use a built-in key type (integer, bigint, uuid, text...), a type of a superuser-installed extension (e.g. citext), or a domain over one.', TG_TABLE_SCHEMA, TG_TABLE_NAME, TG_ARGV[0];
  END IF;

  -- Every row of the statement in one query, from the transition tables. Only the primary key
  -- column is read, instead of converting whole rows to JSON.
  changed := CASE TG_OP
    WHEN 'INSERT' THEN format(
      'SELECT to_jsonb(n.%1$I) #>> ''{}'' AS row_id, ''INSERT'' AS op FROM ${newRows} n',
      TG_ARGV[0])
    WHEN 'DELETE' THEN format(
      'SELECT to_jsonb(o.%1$I) #>> ''{}'' AS row_id, ''DELETE'' AS op FROM ${oldRows} o',
      TG_ARGV[0])
    -- An update that changes primary keys also deletes the old keys that no row has any more
    -- (compared as JSON: the = of a type outside pg_catalog, e.g. citext, is not on the path; the
    -- key type is proven safe above, so to_jsonb here runs no code of a non-superuser role)
    ELSE format(
      'SELECT to_jsonb(o.%1$I) #>> ''{}'' AS row_id, ''DELETE'' AS op FROM ${oldRows} o '
      || 'WHERE NOT EXISTS (SELECT 1 FROM ${newRows} n WHERE to_jsonb(n.%1$I) = to_jsonb(o.%1$I)) '
      || 'UNION ALL SELECT to_jsonb(n.%1$I) #>> ''{}'', ''UPDATE'' FROM ${newRows} n',
      TG_ARGV[0])
  END;
  EXECUTE format(${dollarQuote(
    `
    INSERT INTO %s (table_schema, table_name, row_id, op)
    SELECT $1, $2, changed.row_id, changed.op FROM (%s) AS changed
  `,
    'record'
  )}, ${CHANGELOG_LITERAL_TOKEN}, changed) USING TG_TABLE_SCHEMA, TG_TABLE_NAME;${notifyChanged}${pruneCall('  ')}
  RETURN NULL;
END;
`
  )};
COMMENT ON FUNCTION ${functionName}() IS ${quoteLiteral(`${LILYPAD_CHANGELOG_VERSION_PREFIX}${LILYPAD_CHANGELOG_VERSION}`)};
-- Only its owner writes the changelog (a role granted a write explicitly keeps it: lilypad-doctor
-- reports it), and only the triggers run the functions
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON ${quotedTable} FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION ${functionName}() FROM PUBLIC;
${prune ? `REVOKE EXECUTE ON FUNCTION ${pruneFunction}() FROM PUBLIC;` : `DROP FUNCTION IF EXISTS ${pruneFunction}();`}
`;
}

/**
 * The `DO` block that creates the trigger function from `body`, where it replaces the placeholders
 * with the changelog table and the prune function qualified with their schemas, known only there.
 * The body becomes the format string of one `format()` (its `%` escaped, the placeholders turned
 * into `%1$s`, `%2$s` and `%3$s`): unlike nested `replace()` calls, it never reads again the names
 * it inserted, which may contain a placeholder.
 */
function recordDoBody(
  functionName: string,
  quotedTable: string,
  pruneFunction: string | undefined,
  body: string
): string {
  const qualify = (name: string, query: string) => `
  ${name} text := (
    ${query}
  );`;
  // The body holds no name of the config but the notification channel, which cannot contain a
  // placeholder (see lilypadChangelogSql)
  const template = escapeFormat(body)
    .replaceAll(CHANGELOG_LITERAL_TOKEN, '%2$s')
    .replaceAll(CHANGELOG_TOKEN, '%1$s')
    .replaceAll(PRUNE_TOKEN, '%3$s');
  return dollarQuote(
    `
DECLARE${qualify(
      'changelog',
      `SELECT format('%I.%I', n.nspname, c.relname)
    FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = ${quoteLiteral(quotedTable)}::regclass`
    )}${
      pruneFunction === undefined
        ? ''
        : qualify(
            'prune',
            `SELECT format('%I.%I', n.nspname, p.proname)
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE p.oid = ${quoteLiteral(`${pruneFunction}()`)}::regprocedure`
          )
    }
BEGIN
  EXECUTE format(
    'CREATE OR REPLACE FUNCTION %s() RETURNS trigger AS %L LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, pg_temp',
    ${quoteLiteral(functionName)},
    format(${dollarQuote(template)}, changelog, quote_literal(changelog)${pruneFunction === undefined ? '' : ', prune'})
  );
END
`,
    'lilypad'
  );
}

export type LilypadChangelogPruneScheduleOptions = {
  /**
   * The retention, in milliseconds: the rows older than this are deleted. It must be much longer
   * than the `maxGap` and the `lookback` of the caches, and than the longest transaction (e.g. 24 h).
   */
  olderThan: number;
  /** When the job runs, in cron syntax (pg_cron uses UTC). Defaults to `0 3 * * *`: daily at 3:00. */
  schedule?: string | undefined;
  /** Name of the changelog table, if not the default one. */
  changelogTable?: string | undefined;
  /**
   * Name of the job. Defaults to `<changelog table>_prune` (never shortened: a job name is not an
   * identifier). Scheduling it again replaces it.
   */
  jobName?: string | undefined;
  /**
   * Accepts an `olderThan` below one hour ({@link LILYPAD_MIN_CHANGELOG_RETENTION}), which
   * otherwise throws: it deletes rows that the caches may still have to read.
   */
  force?: boolean | undefined;
  /**
   * The database of the changelog table, when pg_cron is installed in another one (see
   * `cron.database_name`): the SQL then runs in the pg_cron database, and the job resolves
   * `changelogTable` with the search_path of its role, so qualify it with its schema. Without it,
   * the SQL runs in the database of the changelog, which must be the pg_cron one.
   */
  database?: string | undefined;
};

/**
 * The SQL that schedules a pg_cron job deleting the changelog rows older than `olderThan`: the
 * database then prunes its changelog itself. Run it once, in a migration, with pg_cron installed
 * (`CREATE EXTENSION pg_cron`). Running it again updates the job.
 */
export function lilypadChangelogPruneScheduleSql(
  options: LilypadChangelogPruneScheduleOptions
): string {
  assertNumberOption(
    'lilypadChangelogPruneScheduleSql',
    'olderThan',
    options.olderThan,
    'positive'
  );
  assertRetention(
    'lilypadChangelogPruneScheduleSql',
    'olderThan',
    options.olderThan,
    options.force
  );
  const table = options.changelogTable ?? LILYPAD_DEFAULT_CHANGELOG_TABLE;
  // Not pruneFunctionName, which shortens a long name: a job of an earlier version would remain
  const jobName = quoteLiteral(options.jobName ?? `${identifierPrefix(table)}_prune`);
  const schedule = quoteLiteral(options.schedule ?? '0 3 * * *');
  const condition = olderThanCondition(options.olderThan);
  if (options.database !== undefined) {
    const command = `DELETE FROM ${quoteIdentifier(table)} WHERE ${condition}`;
    return `SELECT cron.schedule_in_database(${jobName}, ${schedule}, ${quoteLiteral(command)}, ${quoteLiteral(options.database)});
`;
  }
  // The table is qualified with its schema now: the job runs with the search_path of its role
  return `SELECT cron.schedule(${jobName}, ${schedule}, format(
  'DELETE FROM %I.%I WHERE ${condition}',
  n.nspname, c.relname
))
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.oid = ${quoteLiteral(quoteIdentifier(table))}::regclass;
`;
}

/**
 * The SQL that attaches the changelog triggers to a cached table: one statement trigger for each of
 * INSERT, UPDATE and DELETE, which records all the rows of a statement in one query (through its
 * transition tables), and one for `TRUNCATE`. It drops the row trigger of the versions 3 and
 * earlier, which the trigger function no longer serves. Run it once per table, in a migration (in one transaction, so that no write goes
 * unrecorded), after {@link lilypadChangelogSql}.
 *
 * The statement triggers of a partition (or an inheritance child) fire only for the statements that
 * name it, not for the writes made through its parent: attach them to the partitioned table itself.
 *
 * @param options.table - The cached table (`table` or `schema.table`).
 * @param options.primaryKey - Its primary key column.
 * @param options.changelogTable - The changelog table, if not the default one.
 */
export function lilypadChangelogTriggerSql(options: {
  table: string;
  primaryKey: string;
  changelogTable?: string | undefined;
}): string {
  const changelogTable = options.changelogTable ?? LILYPAD_DEFAULT_CHANGELOG_TABLE;
  const names = changelogTriggerNames(options.table);
  const table = quoteIdentifier(options.table);
  // The names of versions 5 and earlier that were too long, as PostgreSQL truncated them
  const dropUnshortened = Object.values(changelogTriggerNames(options.table, true))
    .filter((name) => !Object.values(names).includes(name))
    .map((name) => `DROP TRIGGER IF EXISTS ${quoteIdentifier(name)} ON ${table};\n`)
    .join('');
  const execute = `EXECUTE FUNCTION ${quoteIdentifier(triggerFunctionName(changelogTable))}(${quoteLiteral(options.primaryKey)})`;
  const oldRows = LILYPAD_CHANGELOG_OLD_ROWS;
  const newRows = LILYPAD_CHANGELOG_NEW_ROWS;
  return `${dropUnshortened}DROP TRIGGER IF EXISTS ${quoteIdentifier(names.legacyRow)} ON ${table};
DROP TRIGGER IF EXISTS ${quoteIdentifier(names.insert)} ON ${table};
CREATE TRIGGER ${quoteIdentifier(names.insert)}
  AFTER INSERT ON ${table} REFERENCING NEW TABLE AS ${newRows}
  FOR EACH STATEMENT ${execute};
DROP TRIGGER IF EXISTS ${quoteIdentifier(names.update)} ON ${table};
CREATE TRIGGER ${quoteIdentifier(names.update)}
  AFTER UPDATE ON ${table} REFERENCING OLD TABLE AS ${oldRows} NEW TABLE AS ${newRows}
  FOR EACH STATEMENT ${execute};
DROP TRIGGER IF EXISTS ${quoteIdentifier(names.delete)} ON ${table};
CREATE TRIGGER ${quoteIdentifier(names.delete)}
  AFTER DELETE ON ${table} REFERENCING OLD TABLE AS ${oldRows}
  FOR EACH STATEMENT ${execute};
DROP TRIGGER IF EXISTS ${quoteIdentifier(names.truncate)} ON ${table};
CREATE TRIGGER ${quoteIdentifier(names.truncate)}
  AFTER TRUNCATE ON ${table}
  FOR EACH STATEMENT ${execute};
`;
}

/**
 * A change recorded by the changelog: a change of one row, or a `TRUNCATE` of the table (which
 * removed every row, and has no `rowId`).
 */
export type LilypadChange = {
  /** The id of the changelog row. */
  id: string;
  /** The transaction that made the change. */
  xid: bigint;
} & ({ rowId: string; op: 'INSERT' | 'UPDATE' | 'DELETE' } | { rowId: null; op: 'TRUNCATE' });

/**
 * Where the next read of the changelog starts: the transactions that a read could not see yet.
 * They are the ones still running when it read (`xip`) and the ones that had not started
 * (`xid >= xmax`): every other transaction had already committed or aborted, so its changes were
 * visible to that read.
 */
export type LilypadChangelogCursor = {
  /** The first transaction id not yet assigned when the read took its snapshot. */
  xmax: bigint;
  /** The transactions running when the read took its snapshot. */
  xip: bigint[];
};

/** What to read of a table: the changes since a cursor, or those of the last `lookback` ms. */
export type LilypadChangesRequest = {
  tableName: string;
  since: { cursor: LilypadChangelogCursor } | { lookback: number };
};

/**
 * Whether the changes of the transaction `xid` were visible to the read that produced `cursor`:
 * a later read from this cursor does not return them.
 */
export function lilypadCursorCovers(cursor: LilypadChangelogCursor, xid: bigint): boolean {
  return xid < cursor.xmax && !cursor.xip.includes(xid);
}

/**
 * Reads the changes of a table since `cursor`, and the cursor for the next read.
 *
 * The cursor holds the transactions the read could not see yet (see
 * {@link LilypadChangelogCursor}): the next read returns exactly the changes of those
 * transactions that are visible to it, whatever the order of the commits. Each change is thus
 * returned once, and a long-running transaction does not make every read return again all the
 * changes made since it started.
 *
 * Without a cursor (first read, or a cursor no longer trusted), `since.lookback` returns the
 * changes recorded in the last `lookback` milliseconds instead.
 *
 * `tableName` is resolved as the gate's queries resolve it (with the `search_path` when it is not
 * qualified), so a table of the same name in another schema is not mixed up with it.
 */
export async function readLilypadChanges(
  gate: LilypadDbGate,
  options: LilypadChangesRequest & { changelogTable?: string | undefined }
): Promise<{ changes: LilypadChange[]; cursor: LilypadChangelogCursor }> {
  const { changes, cursor } = await readLilypadChangesBatch(gate, {
    requests: [{ tableName: options.tableName, since: options.since }],
    changelogTable: options.changelogTable,
  });
  return { changes: changes[0] ?? [], cursor };
}

/**
 * Like {@link readLilypadChanges}, for several tables in one query: `changes[i]` holds the changes
 * of `requests[i]`. Every request shares the cursor for the next read.
 */
export async function readLilypadChangesBatch(
  gate: LilypadDbGate,
  options: { requests: LilypadChangesRequest[]; changelogTable?: string | undefined }
): Promise<{ changes: LilypadChange[][]; cursor: LilypadChangelogCursor }> {
  gate.assertOpen();
  const sql = gate.sql;
  const changelogTable = sql(options.changelogTable ?? LILYPAD_DEFAULT_CHANGELOG_TABLE);
  // Passed as text arrays: an empty xmax selects the lookback of the request, and the running
  // transactions of each cursor are joined by commas
  const tableRefs = options.requests.map((request) => quoteIdentifier(request.tableName));
  const cursors = options.requests.map((request) =>
    'cursor' in request.since ? request.since.cursor : undefined
  );
  const xmaxes = cursors.map((cursor) => cursor?.xmax.toString() ?? '');
  const xips = cursors.map((cursor) => cursor?.xip.join(',') ?? '');
  const lookbacks = options.requests.map((request) =>
    'lookback' in request.since ? String(request.since.lookback / 1000) : '0'
  );

  // One statement, so the snapshot and the rows are read together even through a pooler: the
  // snapshot functions return the snapshot the statement reads with.
  const rows = await sql`
    WITH snapshot AS (
      SELECT pg_snapshot_xmax(current.s)::text AS next_xmax,
        (SELECT coalesce(string_agg(x::text, ','), '') FROM pg_snapshot_xip(current.s) AS x) AS next_xip
      FROM (SELECT pg_current_snapshot() AS s) AS current
    ),
    requests AS (
      SELECT (r.ordinality - 1)::int AS request, r.table_ref,
        NULLIF(r.since_xmax, '')::xid8 AS since_xmax,
        string_to_array(NULLIF(r.since_xip, ''), ',')::xid8[] AS since_xip,
        r.lookback_secs::float8 AS lookback_secs
      FROM unnest(
        ${textArrayLiteral(tableRefs)}::text[], ${textArrayLiteral(xmaxes)}::text[],
        ${textArrayLiteral(xips)}::text[], ${textArrayLiteral(lookbacks)}::text[]
      ) WITH ORDINALITY AS r(table_ref, since_xmax, since_xip, lookback_secs, ordinality)
    ),
    -- next_xmax: a row of a transaction the snapshot cannot see yet (xid >= xmax) was not written
    -- by the triggers of that transaction, but with a forged xid: read again by every later read
    -- from a cursor, it would be applied at each of them
    targets AS (
      SELECT requests.*, n.nspname AS schema_name, t.relname AS rel_name,
        pg_snapshot_xmax(pg_current_snapshot()) AS next_xmax
      FROM requests
      JOIN pg_class t ON t.oid = to_regclass(requests.table_ref)
      JOIN pg_namespace n ON n.oid = t.relnamespace
    )
    SELECT snapshot.next_xmax, snapshot.next_xip, targets.request,
      c.id::text AS id, c.xid::text AS xid, c.row_id, c.op
    FROM snapshot
    LEFT JOIN targets ON true
    LEFT JOIN LATERAL (
      SELECT c.id, c.xid, c.row_id, c.op FROM ${changelogTable} c
      WHERE targets.since_xmax IS NOT NULL
        AND c.table_name = targets.rel_name
        AND c.table_schema = targets.schema_name
        AND (c.xid >= targets.since_xmax OR c.xid = ANY(targets.since_xip))
        AND c.xid < targets.next_xmax
      UNION ALL
      SELECT c.id, c.xid, c.row_id, c.op FROM ${changelogTable} c
      WHERE targets.since_xmax IS NULL
        AND c.table_name = targets.rel_name
        AND c.table_schema = targets.schema_name
        AND c.changed_at >= clock_timestamp() - make_interval(secs => targets.lookback_secs)
        AND c.xid < targets.next_xmax
    ) c ON true
    ORDER BY c.id
  `;

  const changes: LilypadChange[][] = options.requests.map(() => []);
  for (const row of rows) {
    // A row change without a row id cannot be applied
    if (row.id !== null && (row.row_id !== null || row.op === 'TRUNCATE')) {
      changes[row.request as number]?.push({
        id: row.id as string,
        xid: BigInt(row.xid as string),
        rowId: row.row_id as string | null,
        op: row.op as LilypadChange['op'],
      } as LilypadChange);
    }
  }
  const nextXmax: unknown = rows[0]?.next_xmax;
  const nextXip: unknown = rows[0]?.next_xip;
  if (typeof nextXmax !== 'string' || typeof nextXip !== 'string') {
    throw new Error('Reading the changelog returned no snapshot.');
  }
  const cursor: LilypadChangelogCursor = {
    xmax: BigInt(nextXmax),
    xip: nextXip === '' ? [] : nextXip.split(',').map((xid) => BigInt(xid)),
  };
  return { changes, cursor };
}

/**
 * The Postgres literal of a `text[]`, passed as a string parameter. Not `sql.array()`: postgres.js
 * registers the array types of a client once its first connection has fetched them, but builds
 * the first query of that connection before, so an array sent by the first query of a process is
 * serialized as `a,b` (malformed array literal), with or without an explicit type.
 */
export function textArrayLiteral(values: readonly string[]): string {
  return `{${values.map((value) => `"${value.replace(/[\\"]/g, '\\$&')}"`).join(',')}}`;
}

/**
 * Deletes the changelog rows older than `olderThan` milliseconds, in batches of `batchSize` rows
 * (one statement each, so that no statement locks or rewrites the whole table). Call it
 * periodically (e.g. from a scheduled job): `olderThan` must be much larger than the `maxGap` and
 * the `lookback` of the caches, and than the longest transaction.
 *
 * @param options.olderThan - The retention, in **milliseconds**. Below one hour it throws, unless
 * `force` is set: a shorter retention deletes rows that the caches may still have to read, and
 * they would miss these changes without knowing it.
 * @param options.batchSize - The most rows one statement deletes. Defaults to 10000.
 * @returns The number of deleted rows.
 */
export async function pruneLilypadChangelog(
  gate: LilypadDbGate,
  options: {
    olderThan: number;
    changelogTable?: string | undefined;
    batchSize?: number | undefined;
    force?: boolean | undefined;
  }
): Promise<number> {
  const owner = 'pruneLilypadChangelog';
  assertNumberOption(owner, 'olderThan', options.olderThan, 'non-negative');
  assertNumberOption(owner, 'batchSize', options.batchSize, 'positive-integer');
  assertRetention(owner, 'olderThan', options.olderThan, options.force);
  gate.assertOpen();
  const changelogTable = gate.sql(options.changelogTable ?? LILYPAD_DEFAULT_CHANGELOG_TABLE);
  const batchSize = options.batchSize ?? 10_000;
  let deleted = 0;
  while (true) {
    const result = await gate.sql`
      DELETE FROM ${changelogTable} WHERE id IN (
        SELECT id FROM ${changelogTable}
        WHERE changed_at < clock_timestamp() - make_interval(secs => ${options.olderThan / 1000})
        ORDER BY changed_at
        LIMIT ${batchSize}
      )
    `;
    deleted += result.count;
    if (result.count < batchSize) {
      return deleted;
    }
  }
}
