import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach, vi } from 'vitest';
import { PostgreSqlContainer, type StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import postgres from 'postgres';
import { LilypadDbGate } from './LilypadDbGate';
import { LilypadDbEmptyWriteError, LilypadDbNotFoundError } from '@/dbConfig/LilypadDbSchema';
import { defineLilypadDb, defineLilypadTable } from '@/dbConfig/LilypadDbConfig';
import { bindLilypadDbHooks, type LilypadDbTableHooks } from '@/dbConfig/LilypadDbHooks';
import { LilypadDbCache } from '@/cache/LilypadDbCache';
import { LilypadDbTable } from './LilypadDbTable';
import {
  lilypadChangelogPruneScheduleSql,
  lilypadChangelogSql,
  lilypadChangelogTriggerSql,
  pruneLilypadChangelog,
  readLilypadChanges,
  readLilypadChangesBatch,
} from './LilypadChangelog';
import {
  checkLilypadSchema,
  LilypadSchemaCheckError,
  readLilypadSchemaFacts,
  type LilypadSchemaCheckOptions,
} from './LilypadSchemaCheck';
import { lilypadSchemaCheckOptions, runLilypadDoctor } from './LilypadDoctor';
import type { LilypadLoggerType } from '@/logger/LilypadLogger';

type User = { id: number; name: string; role: string };

const usersInput = defineLilypadTable<User, 'id'>({
  tableName: 'users',
  primaryKey: 'id',
  generatedPrimaryKey: true,
  cols: { id: { type: 'number' }, name: { type: 'string' }, role: { type: 'string' } },
});

/** The `users` table of a config, with these changes of its description. */
const usersTable = (changes: Partial<typeof usersInput> = {}) =>
  defineLilypadDb({
    tables: { users: defineLilypadTable<User, 'id'>({ ...usersInput, ...changes }) },
  }).tables.users;

const usersSchema = usersTable();

/** The `users` table, with these hooks bound to it. */
const usersWithHooks = (hooks: LilypadDbTableHooks<User>) =>
  bindLilypadDbHooks(defineLilypadDb({ tables: { users: usersInput } }), { users: hooks }).tables
    .users;

const createMockLogger = () =>
  ({
    error: vi.fn(),
    warn: vi.fn(),
    info: vi.fn(),
    debug: vi.fn(),
  }) as unknown as LilypadLoggerType<'error' | 'warn' | 'info' | 'debug'>;

describe('LilypadDbGate (integration)', () => {
  let container: StartedPostgreSqlContainer;
  let admin: postgres.Sql;
  let gate: LilypadDbGate;

  beforeAll(async () => {
    container = await new PostgreSqlContainer('postgres:16-alpine').start();
    admin = postgres(container.getConnectionUri(), { onnotice: () => {} });
    await admin`
      CREATE TABLE users (
        id serial PRIMARY KEY,
        name text NOT NULL,
        role text NOT NULL DEFAULT 'user',
        is_admin boolean NOT NULL DEFAULT false
      )
    `;
    // The notification contract expected by LilypadDbCache's default listener
    await admin`
      CREATE FUNCTION notify_cache_events() RETURNS trigger AS $$
      BEGIN
        IF TG_OP = 'TRUNCATE' THEN
          PERFORM pg_notify('cache_events', json_build_object(
            'table', TG_TABLE_NAME, 'op', TG_OP
          )::text);
          RETURN NULL;
        END IF;
        PERFORM pg_notify('cache_events', json_build_object(
          'table', TG_TABLE_NAME,
          'id', COALESCE(NEW.id, OLD.id),
          'op', TG_OP
        )::text);
        RETURN NULL;
      END;
      $$ LANGUAGE plpgsql
    `;
    await admin`
      CREATE TRIGGER users_cache_events AFTER INSERT OR UPDATE OR DELETE ON users
      FOR EACH ROW EXECUTE FUNCTION notify_cache_events()
    `;
    await admin`
      CREATE TRIGGER users_cache_events_truncate AFTER TRUNCATE ON users
      FOR EACH STATEMENT EXECUTE FUNCTION notify_cache_events()
    `;
    await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
    await admin.unsafe(lilypadChangelogTriggerSql({ table: 'users', primaryKey: 'id' }));
    gate = await LilypadDbGate.create({
      connectionString: container.getConnectionUri(),
      listen: [],
    });
  });

  afterAll(async () => {
    await gate?.close();
    await admin?.end();
    await container?.stop();
  });

  beforeEach(async () => {
    // The changelog records the TRUNCATE of users: it is emptied afterwards
    await admin`TRUNCATE users RESTART IDENTITY`;
    await admin`TRUNCATE lilypad_cache_changes RESTART IDENTITY`;
  });

  describe('CRUD', () => {
    it('should insert a row and return it with the generated primary key', async () => {
      const { row: created } = await gate.table(usersSchema).insert({
        name: 'Ada',
        role: 'dev',
      });

      expect(created).toEqual({ id: 1, name: 'Ada', role: 'dev' });
    });

    it('should ignore the primary key of the data when it is generated by the database', async () => {
      const { row: created } = await gate.table(usersSchema).insert({
        id: 999,
        name: 'Ada',
        role: 'dev',
      });

      expect(created?.id).toBe(1);
    });

    it('should require the primary key when it is not generated by the database', async () => {
      const schema = usersTable({ generatedPrimaryKey: false });

      await expect(gate.table(schema).insert({ name: 'Ada', role: 'dev' })).rejects.toThrow(
        'Primary key "id" is missing in the insert data for table "users".'
      );
    });

    it('should never write properties that are not schema columns', async () => {
      const payload = { name: 'Mallory', role: 'user', is_admin: true } as unknown as User;

      await gate.table(usersSchema).insert(payload);
      await gate.table(usersSchema).update({ ...payload, id: 1 });

      const [row] = await admin`SELECT is_admin FROM users WHERE id = 1`;
      expect(row!.is_admin).toBe(false);
    });

    it('should select only the schema columns', async () => {
      await admin`INSERT INTO users (name, role, is_admin) VALUES ('Ada', 'dev', true)`;

      expect(await gate.table(usersSchema).selectAll()).toEqual([
        { id: 1, name: 'Ada', role: 'dev' },
      ]);
      expect(await gate.table(usersSchema).selectByPrimaryKey(1)).toEqual({
        id: 1,
        name: 'Ada',
        role: 'dev',
      });
      expect(await gate.table(usersSchema).selectByPrimaryKey(2)).toBeNull();
    });

    it('should pass the whole row to the select hook', async () => {
      await admin`INSERT INTO users (name, role, is_admin) VALUES ('Ada', 'dev', true)`;
      const select = vi.fn((row: unknown) => row as User);

      await gate.table(usersWithHooks({ select })).selectAll();

      expect(select).toHaveBeenCalledWith(expect.objectContaining({ is_admin: true }));
    });

    it('should select the rows of several primary keys in one query', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada'), ('Grace'), ('Linus')`;

      const rows = await gate.table(usersSchema).selectByPrimaryKeys([1, 3, 42]);

      expect(rows.map((row) => row.name).sort()).toEqual(['Ada', 'Linus']);
      expect(await gate.table(usersSchema).selectByPrimaryKeys([])).toEqual([]);
    });

    it('should update a row and return it', async () => {
      await gate.table(usersSchema).insert({ name: 'Ada', role: 'dev' });

      const { row: updated } = await gate.table(usersSchema).update({
        id: 1,
        name: 'Ada',
        role: 'admin',
      });

      expect(updated).toEqual({ id: 1, name: 'Ada', role: 'admin' });
    });

    it('should throw a LilypadDbNotFoundError when updating a row that does not exist', async () => {
      const updating = gate.table(usersSchema).update({ id: 42, name: 'Ghost', role: 'user' });

      await expect(updating).rejects.toThrow(
        'No row with primary key "42" found in table "users".'
      );
      await expect(updating).rejects.toBeInstanceOf(LilypadDbNotFoundError);
      await expect(updating).rejects.toMatchObject({ tableName: 'users', primaryKeyValue: 42 });
    });

    it('should require the primary key to update, even when it is generated', async () => {
      await expect(
        gate.table(usersSchema).update({ name: 'Ada', role: 'dev' } as User)
      ).rejects.toThrow('Primary key "id" is missing in the update data for table "users".');
    });

    it('should delete a row', async () => {
      await gate.table(usersSchema).insert({ name: 'Ada', role: 'dev' });

      const deleted = await gate.table(usersSchema).delete(1);

      expect(deleted).toEqual({ deleted: true, xid: expect.any(BigInt) as bigint });
      expect(await gate.table(usersSchema).selectAll()).toEqual([]);
      expect(await gate.table(usersSchema).delete(1)).toEqual({ deleted: false });
    });

    it('should write the result of the write hook, which can remove properties', async () => {
      const schema = usersWithHooks({ write: ({ role: _role, ...rest }) => rest });

      const { row: created } = await gate.table(schema).insert({ name: 'Mallory', role: 'admin' });

      expect(created?.role).toBe('user');
    });

    it('should skip undefined values instead of failing', async () => {
      // e.g. an optional field of a request body that was not sent
      const data = { name: 'Ada', role: undefined as unknown as string };

      const { row: created } = await gate.table(usersSchema).insert(data);

      expect(created).toEqual({ id: 1, name: 'Ada', role: 'user' });
    });

    it('should update only the columns present in the data', async () => {
      await gate.table(usersSchema).insert({ name: 'Ada', role: 'dev' });

      const { row: updated } = await gate.table(usersSchema).update({ id: 1, role: 'admin' });

      expect(updated).toEqual({ id: 1, name: 'Ada', role: 'admin' });
    });

    it('should return only the schema columns of a written row, unless a select hook reads it', async () => {
      const seen: unknown[] = [];
      const schema = usersWithHooks({
        select: (row) => {
          seen.push(row);
          return row as User;
        },
      });

      const { row: plain } = await gate.table(usersSchema).insert({ name: 'Ada', role: 'dev' });
      await gate.table(schema).insert({ name: 'Grace', role: 'dev' });

      expect(Object.keys(plain!).sort()).toEqual(['id', 'name', 'role']);
      // The select hook receives the whole row, as when it selects
      expect(seen[0]).toMatchObject({ is_admin: false });
    });

    it('should select tables larger than one cursor batch', async () => {
      await admin`INSERT INTO users (name) SELECT 'user' || i FROM generate_series(1, 2500) AS i`;

      expect(await gate.table(usersSchema).selectAll()).toHaveLength(2500);
    });

    it('should stop reading a table once its signal is aborted', async () => {
      await admin`INSERT INTO users (name) SELECT 'user' || i FROM generate_series(1, 2500) AS i`;
      const controller = new AbortController();

      const reading = gate.table(usersSchema).selectAll({ signal: controller.signal });
      controller.abort(new Error('timed out'));

      await expect(reading).rejects.toThrow('timed out');
      await expect(
        gate.table(usersSchema).selectAll({ signal: controller.signal })
      ).rejects.toThrow('timed out');
      // The cursor was closed: the connection is usable again
      expect(await gate.table(usersSchema).selectAll()).toHaveLength(2500);
    });

    it('should cancel queries longer than statementTimeout on the server', async () => {
      const limitedGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        statementTimeout: 100,
      });

      await expect(limitedGate.sql`SELECT pg_sleep(1)`).rejects.toThrow('statement timeout');
      await limitedGate.close();
    });

    it('should escape table names', async () => {
      const schema = usersTable({ tableName: 'users; DROP TABLE users; --' });

      await expect(gate.table(schema).selectAll()).rejects.toThrow('does not exist');
      const [check] = await admin`SELECT to_regclass('users') IS NOT NULL AS exists`;
      expect(check?.exists).toBe(true);
    });
  });

  describe('listeners', () => {
    it('should deliver notifications to every callback of the channel', async () => {
      const first = vi.fn();
      const second = vi.fn();
      await gate.addListener({ channel: 'test_channel', callbackId: 'first', callback: first });
      await gate.addListener({ channel: 'test_channel', callbackId: 'second', callback: second });

      await admin.notify('test_channel', 'hello');

      await vi.waitFor(() => {
        expect(first).toHaveBeenCalledWith('hello');
        expect(second).toHaveBeenCalledWith('hello');
      });
      await gate.removeListener('test_channel', 'first');
      await gate.removeListener('test_channel', 'second');
    });

    it('should log a rejected async callback without affecting the others', async () => {
      const logger = createMockLogger();
      const loggedGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        logger,
        listen: [
          {
            channel: 'failing_channel',
            callbackId: 'failing',
            callback: async () => {
              throw new Error('callback failed');
            },
          },
        ],
      });
      const healthy = vi.fn();
      await loggedGate.addListener({
        channel: 'failing_channel',
        callbackId: 'healthy',
        callback: healthy,
      });

      await admin.notify('failing_channel', 'payload');

      await vi.waitFor(() => {
        expect(healthy).toHaveBeenCalledWith('payload');
        expect(logger.error).toHaveBeenCalledWith(expect.stringContaining('"failing"'), {
          source: loggedGate.id,
          error: expect.any(Error),
        });
      });
      await loggedGate.close();
    });

    it('should stop delivering notifications to removed callbacks', async () => {
      const removed = vi.fn();
      const kept = vi.fn();
      await gate.addListener({
        channel: 'removal_channel',
        callbackId: 'removed',
        callback: removed,
      });
      await gate.addListener({ channel: 'removal_channel', callbackId: 'kept', callback: kept });

      expect(await gate.removeListener('removal_channel', 'removed')).toBe(true);
      await admin.notify('removal_channel', 'payload');

      await vi.waitFor(() => expect(kept).toHaveBeenCalled());
      expect(removed).not.toHaveBeenCalled();
      await gate.removeListener('removal_channel', 'kept');
    });

    it('should share a single LISTEN between concurrent addListener calls', async () => {
      const first = vi.fn();
      const second = vi.fn();

      await Promise.all([
        gate.addListener({ channel: 'concurrent_channel', callbackId: 'first', callback: first }),
        gate.addListener({ channel: 'concurrent_channel', callbackId: 'second', callback: second }),
      ]);
      await admin.notify('concurrent_channel', 'payload');

      await vi.waitFor(() => {
        expect(first).toHaveBeenCalledOnce();
        expect(second).toHaveBeenCalledOnce();
      });
      await gate.removeListener('concurrent_channel', 'first');
      await gate.removeListener('concurrent_channel', 'second');
    });
  });

  describe('listener lifecycle', () => {
    it('should call onReconnect once the listener connection is re-established', async () => {
      const callback = vi.fn();
      const onReconnect = vi.fn();
      const reconnectingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listen: [{ channel: 'reconnect_channel', callbackId: 'cb', callback, onReconnect }],
        listenHeartbeat: false,
      });
      expect(onReconnect).not.toHaveBeenCalled();

      await admin`
        SELECT pg_terminate_backend(pid) FROM pg_stat_activity
        WHERE query ILIKE 'listen%reconnect_channel%'
      `;

      await vi.waitFor(() => expect(onReconnect).toHaveBeenCalledOnce(), { timeout: 10000 });
      await admin.notify('reconnect_channel', 'after');
      await vi.waitFor(() => expect(callback).toHaveBeenCalledWith('after'));
      await reconnectingGate.close();
    });

    it('should remove a callback whose LISTEN is still pending', async () => {
      const callback = vi.fn();
      const adding = gate.addListener({ channel: 'pending_channel', callbackId: 'cb', callback });

      expect(await gate.removeListener('pending_channel', 'cb')).toBe(true);
      await adding;
      await admin.notify('pending_channel', 'payload');
      await new Promise((resolve) => setTimeout(resolve, 200));

      expect(callback).not.toHaveBeenCalled();
    });

    it('should report the LISTEN connection as healthy while heartbeats come back', async () => {
      const beatingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listenHeartbeat: 100,
      });
      expect(beatingGate.isListenHealthy()).toBe(false);

      await beatingGate.addListener({
        channel: 'beating_channel',
        callbackId: 'cb',
        callback: vi.fn(),
      });
      await new Promise((resolve) => setTimeout(resolve, 400));
      expect(beatingGate.isListenHealthy()).toBe(true);

      await beatingGate.removeListener('beating_channel', 'cb');
      expect(beatingGate.isListenHealthy()).toBe(false);
      await beatingGate.close();
    });

    it('should report the LISTEN connection as unhealthy when heartbeats stop coming back', async () => {
      const beatingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listenHeartbeat: 100,
        listen: [{ channel: 'silent_channel', callbackId: 'cb', callback: vi.fn() }],
      });
      // The heartbeats are sent to a channel nobody listens to any more
      Object.assign(beatingGate, { heartbeatChannel: 'lilypad_heartbeat_elsewhere' });

      await vi.waitFor(() => expect(beatingGate.isListenHealthy()).toBe(false), { timeout: 2000 });
      await beatingGate.close();
    });

    it('should close a gate that still has active listeners', async () => {
      const closingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listen: [{ channel: 'closing_channel', callbackId: 'cb', callback: vi.fn() }],
      });

      await expect(closingGate.close()).resolves.toBeUndefined();
    });
  });

  describe('changelog', () => {
    const readAll = () =>
      readLilypadChanges(gate, { tableName: 'users', since: { lookback: 60_000 } });

    it('should record inserts, updates, deletes and primary key changes', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      await admin`UPDATE users SET role = 'admin' WHERE id = 1`;
      await admin`UPDATE users SET id = 2 WHERE id = 1`;
      await admin`DELETE FROM users WHERE id = 2`;

      const { changes } = await readAll();

      expect(changes.map(({ op, rowId }) => `${op}:${rowId}`)).toEqual([
        'INSERT:1',
        'UPDATE:1',
        'DELETE:1', // the primary key change removes the old key...
        'UPDATE:2', // ...and updates the new one
        'DELETE:2',
      ]);
    });

    it('should record every row of a statement, with the primary key changes', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada'), ('Grace'), ('Alan')`;
      await admin`UPDATE users SET id = id + 10 WHERE id <= 2`;
      await admin`UPDATE users SET role = 'admin'`;
      await admin`DELETE FROM users WHERE id > 10`;

      const { changes } = await readAll();

      expect(changes.map(({ op, rowId }) => `${op}:${rowId}`)).toEqual([
        'INSERT:1',
        'INSERT:2',
        'INSERT:3',
        'DELETE:1', // no row has the keys 1 and 2 any more...
        'DELETE:2',
        'UPDATE:11', // ...and the new keys are updated
        'UPDATE:12',
        'UPDATE:3',
        'UPDATE:11',
        'UPDATE:12',
        'DELETE:11',
        'DELETE:12',
      ]);
      expect(new Set(changes.slice(0, 3).map((change) => change.xid)).size).toBe(1);
    });

    it('should record nothing for a statement that changes no row', async () => {
      await admin`UPDATE users SET role = 'admin' WHERE id = 42`;

      expect((await readAll()).changes).toEqual([]);
    });

    it('should record TRUNCATE', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      await admin`TRUNCATE users`;

      const { changes } = await readAll();

      expect(changes.map(({ op, rowId }) => `${op}:${rowId}`)).toEqual([
        'INSERT:1',
        'TRUNCATE:null',
      ]);
    });

    it('should return with each write the transaction id that the changelog records', async () => {
      const created = await gate.table(usersSchema).insert({ name: 'Ada', role: 'dev' });
      const updated = await gate.table(usersSchema).update({ id: 1, role: 'admin' });
      const deleted = await gate.table(usersSchema).delete(1);

      const { changes } = await readAll();

      expect(created.row).toEqual({ id: 1, name: 'Ada', role: 'dev' });
      expect(updated.row).toEqual({ id: 1, name: 'Ada', role: 'admin' });
      expect(changes.map((change) => change.xid)).toEqual([created.xid, updated.xid, deleted.xid]);
      expect(await gate.table(usersSchema).delete(1)).toEqual({ deleted: false });
    });

    it('should not miss a transaction that commits after a later one', async () => {
      const slow = await admin.reserve();
      try {
        await slow`BEGIN`;
        await slow`INSERT INTO users (name) VALUES ('slow')`; // id 1, not committed yet
        await admin`INSERT INTO users (name) VALUES ('fast')`; // id 2, committed
        const first = await readAll();
        expect(first.changes.map((change) => change.rowId)).toEqual(['2']);

        await slow`COMMIT`;
        const next = await readLilypadChanges(gate, {
          tableName: 'users',
          since: { cursor: first.cursor },
        });

        // The slow transaction is returned once it commits, and the fast one is not returned again
        expect(next.changes.map((change) => change.rowId)).toEqual(['1']);
      } finally {
        slow.release();
      }
    });

    it('should not return again the changes committed while a long transaction runs', async () => {
      const long = await admin.reserve();
      try {
        await long`BEGIN`;
        // A transaction id, as any writing transaction has (e.g. a long migration)
        await long`SELECT pg_current_xact_id()`;
        await admin`INSERT INTO users (name) VALUES ('first')`;
        const first = await readAll();
        expect(first.cursor.xip.length).toBeGreaterThan(0);

        await admin`INSERT INTO users (name) VALUES ('second')`;
        const second = await readLilypadChanges(gate, {
          tableName: 'users',
          since: { cursor: first.cursor },
        });
        const third = await readLilypadChanges(gate, {
          tableName: 'users',
          since: { cursor: second.cursor },
        });

        expect(second.changes.map((change) => change.rowId)).toEqual(['2']);
        expect(third.changes).toEqual([]);
        await long`ROLLBACK`;
      } finally {
        long.release();
      }
    });

    it('should read several requests in one query, each from its own cursor or lookback', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      const { cursor } = await readAll();
      await admin`INSERT INTO users (name) VALUES ('Grace')`;

      const { changes } = await readLilypadChangesBatch(gate, {
        requests: [
          { tableName: 'users', since: { lookback: 60_000 } },
          { tableName: 'users', since: { cursor } },
          { tableName: 'no_such_table', since: { lookback: 60_000 } },
        ],
      });

      expect(changes.map((list) => list.map((change) => change.rowId))).toEqual([
        ['1', '2'],
        ['2'],
        [],
      ]);
    });

    it('should read the changelog with the first query of a new gate', async () => {
      // postgres.js has not loaded the array types yet when it builds the first query
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      const coldGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
      });

      try {
        const { changes } = await readLilypadChangesBatch(coldGate, {
          requests: [
            { tableName: 'users', since: { lookback: 60_000 } },
            { tableName: 'users', since: { cursor: { xmax: 1n, xip: [1n, 2n] } } },
            { tableName: 'no "such" \\ table', since: { lookback: 60_000 } },
          ],
        });

        expect(changes.map((list) => list.map((change) => change.rowId))).toEqual([
          ['1'],
          ['1'],
          [],
        ]);
      } finally {
        await coldGate.close();
      }
    });

    it('should delete the rows older than the retention', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;

      expect(await pruneLilypadChangelog(gate, { olderThan: 0, force: true })).toBe(1);
      expect((await readAll()).changes).toEqual([]);
    });

    it('should delete the old rows in batches, and count them all', async () => {
      await admin`INSERT INTO users (name) SELECT 'old' FROM generate_series(1, 5)`;
      await admin`INSERT INTO users (name) VALUES ('recent')`;
      await admin`
        UPDATE lilypad_cache_changes SET changed_at = now() - interval '2 hours' WHERE row_id <> '6'
      `;

      expect(await pruneLilypadChangelog(gate, { olderThan: 60 * 60_000, batchSize: 2 })).toBe(5);
      expect((await readAll()).changes.map((change) => change.rowId)).toEqual(['6']);
    });

    describe('pruning', () => {
      /** Records `count` changes, dated two hours ago. */
      const recordOldChanges = async (count: number) => {
        await admin`INSERT INTO users (name) SELECT 'old' FROM generate_series(1, ${count})`;
        await admin`UPDATE lilypad_cache_changes SET changed_at = now() - interval '2 hours'`;
      };
      const countChanges = async () => {
        const [row] = await admin`
          SELECT count(*) FILTER (WHERE changed_at < now() - interval '1 hour')::int AS old,
            count(*) FILTER (WHERE changed_at >= now() - interval '1 hour')::int AS recent
          FROM lilypad_cache_changes
        `;
        return row as { old: number; recent: number };
      };

      describe('from the trigger', () => {
        beforeAll(async () => {
          await admin.unsafe(
            lilypadChangelogSql({
              notifyChannel: false,
              prune: { olderThan: 60 * 60_000, every: 1, batchSize: 2 },
            })
          );
          // A role that can write the cached table and record its changes, but not delete them
          await admin.unsafe(`
            CREATE ROLE lilypad_writer;
            GRANT INSERT, UPDATE ON users TO lilypad_writer;
            GRANT USAGE ON SEQUENCE users_id_seq TO lilypad_writer;
            GRANT INSERT ON lilypad_cache_changes TO lilypad_writer;
            GRANT USAGE ON SEQUENCE lilypad_cache_changes_id_seq TO lilypad_writer;
          `);
        });

        afterAll(async () => {
          await admin.unsafe(`
            DROP OWNED BY lilypad_writer;
            DROP ROLE lilypad_writer;
          `);
          await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
        });

        it('should delete a batch of old rows with a write, even without the DELETE privilege', async () => {
          await recordOldChanges(3);

          await admin.begin(async (tx) => {
            await tx`SET LOCAL ROLE lilypad_writer`;
            await tx`INSERT INTO users (name) VALUES ('Ada')`;
          });

          expect(await countChanges()).toEqual({ old: 1, recent: 1 });
        });

        it('should not prune in a transaction stricter than READ COMMITTED', async () => {
          await recordOldChanges(3);

          await admin.begin('isolation level repeatable read', async (tx) => {
            await tx`INSERT INTO users (name) VALUES ('Ada')`;
          });

          expect(await countChanges()).toEqual({ old: 3, recent: 1 });
        });

        it('should not prune any more once installed without the option', async () => {
          await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
          try {
            await recordOldChanges(3);
            await admin`INSERT INTO users (name) VALUES ('Ada')`;

            expect(await countChanges()).toEqual({ old: 3, recent: 1 });
            const [row] = await admin`
              SELECT to_regprocedure('lilypad_cache_changes_prune()') IS NULL AS dropped
            `;
            expect(row!.dropped).toBe(true);
          } finally {
            await admin.unsafe(
              lilypadChangelogSql({
                notifyChannel: false,
                prune: { olderThan: 60 * 60_000, every: 1, batchSize: 2 },
              })
            );
          }
        });

        it('should keep the pruning in the fix of an outdated changelog', async () => {
          await admin`COMMENT ON FUNCTION lilypad_cache_changes_record() IS 'lilypad-changelog:3'`;
          try {
            const result = await checkLilypadSchema(gate, { tables: [] });

            expect(result.problems[0]!.fix).toBe(
              lilypadChangelogSql({
                notifyChannel: false,
                prune: { olderThan: 60 * 60_000, every: 1, batchSize: 2 },
              })
            );
          } finally {
            await admin`COMMENT ON FUNCTION lilypad_cache_changes_record() IS 'lilypad-changelog:4'`;
          }
        });
      });

      it('should schedule a pg_cron job that deletes the old rows', async () => {
        // pg_cron is not in the image: a stand-in cron.schedule records the job
        await admin.unsafe(`
          CREATE SCHEMA cron;
          CREATE TABLE cron.job (jobname text PRIMARY KEY, schedule text, command text);
          CREATE FUNCTION cron.schedule(job_name text, schedule text, command text) RETURNS bigint AS $$
            INSERT INTO cron.job VALUES (job_name, schedule, command)
            ON CONFLICT (jobname) DO UPDATE SET schedule = excluded.schedule, command = excluded.command;
            SELECT 1::bigint;
          $$ LANGUAGE sql;
        `);
        try {
          await admin.unsafe(lilypadChangelogPruneScheduleSql({ olderThan: 60 * 60_000 }));
          await admin.unsafe(
            lilypadChangelogPruneScheduleSql({ olderThan: 60 * 60_000, schedule: '0 * * * *' })
          );
          const jobs = await admin`SELECT jobname, schedule, command FROM cron.job`;
          expect(jobs).toEqual([
            {
              jobname: 'lilypad_cache_changes_prune',
              schedule: '0 * * * *',
              command:
                'DELETE FROM public.lilypad_cache_changes WHERE changed_at < clock_timestamp() - make_interval(secs => 3600)',
            },
          ]);

          await recordOldChanges(3);
          await admin`INSERT INTO users (name) VALUES ('Ada')`;
          // The job runs in its own session, with the search_path of its role
          await admin.begin(async (tx) => {
            await tx`SET LOCAL search_path TO pg_catalog`;
            await tx.unsafe(jobs[0]!.command as string);
          });

          expect(await countChanges()).toEqual({ old: 0, recent: 1 });
        } finally {
          await admin`DROP SCHEMA cron CASCADE`;
        }
      });

      describe('detected by the schema check', () => {
        const DAY = 24 * 60 * 60_000;
        // A changelog of its own, created for each test: its deletion statistics start at zero
        const changes = 'detected_changes';
        const options = (changelog: { pruning?: 'external' } = {}) => ({
          tables: [],
          changelog: { table: changes, ...changelog },
        });
        const codes = (result: Awaited<ReturnType<typeof checkLilypadSchema>>) =>
          result.problems.map((problem) => problem.code);
        const recordChange = (age: string) =>
          admin.unsafe(`
            INSERT INTO ${changes} (table_name, row_id, op, changed_at)
            VALUES ('users', '1', 'INSERT', now() - interval '${age}')
          `);

        beforeEach(async () => {
          await admin.unsafe(lilypadChangelogSql({ table: changes, notifyChannel: false }));
        });

        afterEach(async () => {
          await admin.unsafe(`
            DROP TABLE ${changes};
            DROP FUNCTION detected_changes_record();
            DROP FUNCTION IF EXISTS detected_changes_prune();
            DROP SCHEMA IF EXISTS cron CASCADE;
          `);
        });

        it('should read that the server has no pg_cron', async () => {
          const facts = await readLilypadSchemaFacts(gate, options());

          expect(facts.cron).toEqual({
            available: false,
            installed: false,
            database: null,
            jobs: null,
          });
          expect(facts.changelog).toMatchObject({
            schema: 'public',
            hasPruneFunction: false,
            oldestRowAge: null,
            deletedRows: 0,
          });
        });

        it('should suggest the prune option of the trigger without pg_cron, as a warning', async () => {
          const result = await checkLilypadSchema(gate, options());

          expect(result.ok).toBe(true);
          expect(codes(result)).toEqual(['no-changelog-pruning']);
          expect(result.problems[0]!.severity).toBe('warning');

          await admin.unsafe(result.problems[0]!.fix!);

          expect((await readLilypadSchemaFacts(gate, options())).changelog.hasPruneFunction).toBe(
            true
          );
          expect(await checkLilypadSchema(gate, options())).toMatchObject({
            ok: true,
            problems: [],
          });
        });

        it('should report a trigger that prunes rows the caches still need, as an error', async () => {
          await admin.unsafe(
            lilypadChangelogSql({
              table: changes,
              notifyChannel: false,
              prune: { olderThan: 30 * 60_000 },
            })
          );

          const result = await checkLilypadSchema(gate, options());
          expect(result.ok).toBe(false);
          expect(codes(result)).toEqual(['short-changelog-retention']);

          await admin.unsafe(result.problems[0]!.fix!);

          expect((await checkLilypadSchema(gate, options())).problems).toEqual([]);
        });

        it('should find a pg_cron job that deletes from the changelog, and read its retention', async () => {
          // pg_cron is not in the image: a stand-in cron.job with the columns of pg_cron 1.6
          await admin.unsafe(`
            CREATE SCHEMA cron;
            CREATE TABLE cron.job (
              jobid bigserial PRIMARY KEY, schedule text, command text, nodename text,
              nodeport int, database text, username text, active boolean DEFAULT true,
              jobname text
            );
            INSERT INTO cron.job (schedule, command, database, username, jobname) VALUES (
              '0 3 * * *',
              'DELETE FROM public.${changes} WHERE changed_at < now() - interval ''2 days''',
              current_database(), current_user, 'prune_changes'
            );
          `);

          const facts = await readLilypadSchemaFacts(gate, options());
          expect(facts.cron.jobs).toEqual([
            {
              id: 1,
              name: 'prune_changes',
              schedule: '0 3 * * *',
              command: `DELETE FROM public.${changes} WHERE changed_at < now() - interval '2 days'`,
              active: true,
              database: facts.database,
            },
          ]);
          expect((await checkLilypadSchema(gate, options())).problems).toEqual([]);

          await admin`UPDATE cron.job SET command = replace(command, '2 days', '1 hour')`;
          const short = await checkLilypadSchema(gate, options());
          expect(codes(short)).toEqual(['short-changelog-retention']);
          expect(short.problems[0]!.fix).toContain(
            "SELECT cron.schedule('prune_changes', '0 3 * * *', format("
          );

          await admin`UPDATE cron.job SET active = false`;
          const inactive = await checkLilypadSchema(gate, options());
          expect(codes(inactive)).toEqual(['no-changelog-pruning']);
          expect(inactive.problems[0]!.message).toContain('"prune_changes" deletes them');
        });

        it('should report a changelog whose oldest row is too old, whatever prunes it', async () => {
          await recordChange('30 days');

          const facts = await readLilypadSchemaFacts(gate, options({ pruning: 'external' }));
          expect(facts.changelog.oldestRowAge).toBeGreaterThan(30 * DAY - 60_000);
          const result = await checkLilypadSchema(gate, options({ pruning: 'external' }));
          expect(codes(result)).toEqual(['unpruned-changelog']);

          await admin.unsafe(result.problems[0]!.fix!);

          expect(
            (await checkLilypadSchema(gate, options({ pruning: 'external' }))).problems
          ).toEqual([]);
        });

        it('should suggest nothing once rows were deleted from the changelog, by a job it cannot see', async () => {
          await recordChange('2 days');
          const connection = await admin.reserve();
          try {
            await connection.unsafe(`DELETE FROM ${changes}`);
            // The session flushes its statistics when it goes idle next, instead of up to 10 s later
            await connection`SELECT pg_stat_force_next_flush()`;
          } finally {
            connection.release();
          }

          await vi.waitFor(
            async () => expect((await checkLilypadSchema(gate, options())).problems).toEqual([]),
            { timeout: 15_000, interval: 200 }
          );
        });
      });
    });

    it('should keep a LilypadDbCache in sync without LISTEN', async () => {
      const cache = await LilypadDbCache.create({
        ttl: 60_000,
        gate,
        table: usersTable({ sync: { strategy: 'changelog', pollInterval: 0 } }),
      });
      await cache.sqlCreate({ name: 'Ada', role: 'dev' });
      expect(await cache.getOrFetch(1)).toMatchObject({ role: 'dev' });

      await admin`UPDATE users SET role = 'admin' WHERE id = 1`;
      expect(await cache.getOrFetch(1)).toMatchObject({ role: 'admin' });

      await admin`INSERT INTO users (name) VALUES ('Grace')`;
      expect([...(await cache.getAll()).values()].map((user) => user.name).sort()).toEqual([
        'Ada',
        'Grace',
      ]);

      await admin`DELETE FROM users WHERE id = 1`;
      expect(await cache.getOrFetch(1)).toBeNull();

      await admin`TRUNCATE users`;
      expect((await cache.getAll()).size).toBe(0);
      await cache.dispose();
    });

    it('should not query again the rows the cache wrote itself', async () => {
      const cache = await LilypadDbCache.create({
        ttl: 60_000,
        gate,
        table: usersTable({ sync: { strategy: 'changelog', pollInterval: 0 } }),
      });
      await cache.getAll();
      const created = await cache.sqlCreate({ name: 'Ada', role: 'dev' });
      const updated = await cache.sqlUpdate({ id: created!.id, role: 'admin' });
      const queries = [
        vi.spyOn(LilypadDbTable.prototype, 'selectAll'),
        vi.spyOn(LilypadDbTable.prototype, 'selectByPrimaryKey'),
        vi.spyOn(LilypadDbTable.prototype, 'selectByPrimaryKeys'),
      ];
      try {
        expect([...(await cache.getAll()).values()]).toEqual([updated]);
        expect(await cache.getOrFetch(created!.id)).toEqual(updated);
        for (const query of queries) {
          expect(query).not.toHaveBeenCalled();
        }
      } finally {
        queries.forEach((query) => query.mockRestore());
        await cache.dispose();
      }
    });

    it('should let LISTEN and the changelog work together', async () => {
      const listened = vi.fn();
      await gate.addListener({ channel: 'cache_events', callbackId: 'both', callback: listened });

      await admin`INSERT INTO users (name) VALUES ('Ada')`;

      await vi.waitFor(() => expect(listened).toHaveBeenCalled());
      expect((await readAll()).changes).toHaveLength(1);
      await gate.removeListener('cache_events', 'both');
    });
  });

  describe('schema check', () => {
    const users = { table: 'users', primaryKey: 'id' };
    const codes = (result: Awaited<ReturnType<typeof checkLilypadSchema>>) =>
      result.problems.map((problem) => problem.code);
    // The pruning has its own tests: here it is declared external, so that the deletions of the
    // other tests (whose statistics are flushed at any time) change no result
    const check = (options: LilypadSchemaCheckOptions) =>
      checkLilypadSchema(gate, {
        ...options,
        changelog:
          options.changelog === false ? false : { pruning: 'external', ...options.changelog },
      });

    it('should find nothing to fix in a database set up with the library SQL', async () => {
      const result = await check({
        tables: [users],
        notifyChannel: 'cache_events', // sent by the custom trigger of the test table
      });

      expect(result).toEqual({
        ok: true,
        problems: [],
        tables: [{ table: 'users', schema: 'public' }],
      });
    });

    it('should report a missing table', async () => {
      const result = await check({
        tables: [{ table: 'missing', primaryKey: 'id' }],
      });

      expect(codes(result)).toEqual(['missing-table']);
      expect(result.tables).toEqual([{ table: 'missing', schema: null }]);
    });

    it('should report a table without the changelog trigger, with the SQL that fixes it', async () => {
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      try {
        const options = { tables: [{ table: 'unwatched', primaryKey: 'id' }] };
        const result = await check(options);
        expect(codes(result)).toEqual(['missing-changelog-trigger']);

        await admin.unsafe(result.problems[0]!.fix!);

        expect((await check(options)).ok).toBe(true);
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should report a disabled changelog trigger', async () => {
      await admin`ALTER TABLE users DISABLE TRIGGER users_lilypad_update`;
      try {
        const result = await check({ tables: [users] });

        expect(codes(result)).toEqual(['missing-changelog-trigger']);
        expect(result.problems[0]!.message).toContain('do not record UPDATE');
        expect(result.problems[0]!.message).toContain('disabled');
      } finally {
        await admin`ALTER TABLE users ENABLE TRIGGER users_lilypad_update`;
      }
    });

    it('should report a changelog trigger that fires only on replicas', async () => {
      await admin`ALTER TABLE users ENABLE REPLICA TRIGGER users_lilypad_delete`;
      try {
        const result = await check({ tables: [users] });

        expect(codes(result)).toEqual(['missing-changelog-trigger']);
        expect(result.problems[0]!.message).toContain('do not record DELETE');
      } finally {
        await admin`ALTER TABLE users ENABLE TRIGGER users_lilypad_delete`;
      }
    });

    it('should report the row trigger of version 3, and replace it with the statement triggers', async () => {
      await admin`CREATE TABLE legacy (id int PRIMARY KEY)`;
      await admin`
        CREATE TRIGGER legacy_lilypad_changes AFTER INSERT OR UPDATE OR DELETE ON legacy
        FOR EACH ROW EXECUTE FUNCTION lilypad_cache_changes_record('id')
      `;
      await admin`
        CREATE TRIGGER legacy_lilypad_truncate AFTER TRUNCATE ON legacy
        FOR EACH STATEMENT EXECUTE FUNCTION lilypad_cache_changes_record('id')
      `;
      try {
        const options = { tables: [{ table: 'legacy', primaryKey: 'id' }] };
        expect(codes(await check(options))).toEqual(['missing-changelog-trigger']);
        // The write goes on, unrecorded (with a warning of the database)
        await admin`INSERT INTO legacy VALUES (1), (2)`;

        await admin.unsafe(lilypadChangelogTriggerSql({ table: 'legacy', primaryKey: 'id' }));
        await admin`INSERT INTO legacy VALUES (3)`;

        const { changes } = await readLilypadChanges(gate, {
          tableName: 'legacy',
          since: { lookback: 60_000 },
        });
        expect(changes.map((change) => change.rowId)).toEqual(['3']);
        const [trigger] = await admin`
          SELECT count(*)::int AS count FROM pg_trigger
          WHERE tgrelid = 'legacy'::regclass AND tgname = 'legacy_lilypad_changes'
        `;
        expect(trigger!.count).toBe(0);
        expect((await check(options)).ok).toBe(true);
      } finally {
        await admin`DROP TABLE legacy`;
      }
    });

    it('should report a table whose TRUNCATE is not recorded', async () => {
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      // The statement triggers without the TRUNCATE one
      await admin.unsafe(lilypadChangelogTriggerSql({ table: 'unwatched', primaryKey: 'id' }));
      await admin`DROP TRIGGER unwatched_lilypad_truncate ON unwatched`;
      try {
        const options = { tables: [{ table: 'unwatched', primaryKey: 'id' }] };
        const result = await check(options);
        expect(codes(result)).toEqual(['missing-truncate-trigger']);

        await admin.unsafe(result.problems[0]!.fix!);

        expect((await check(options)).ok).toBe(true);
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should report a changelog installed by version 2', async () => {
      await admin`COMMENT ON FUNCTION lilypad_cache_changes_record() IS 'lilypad-changelog:2'`;
      try {
        const result = await check({ tables: [] });

        expect(codes(result)).toEqual(['outdated-changelog']);
        expect(result.problems[0]!.message).toContain('version 2');
        // Installed with notifyChannel: false, so the fix sends no notification either
        expect(result.problems[0]!.fix).not.toContain('pg_notify');
      } finally {
        await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
      }
    });

    it('should keep the notifications of an outdated changelog in its fix', async () => {
      await admin.unsafe(lilypadChangelogSql({ notifyChannel: "app'events" }));
      await admin`COMMENT ON FUNCTION lilypad_cache_changes_record() IS 'lilypad-changelog:3'`;
      try {
        const result = await check({ tables: [] });

        expect(codes(result)).toEqual(['outdated-changelog']);
        expect(result.problems[0]!.fix).toBe(lilypadChangelogSql({ notifyChannel: "app'events" }));
      } finally {
        await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
      }
    });

    it('should report a trigger that records another column than the primary key', async () => {
      const result = await check({
        tables: [{ table: 'users', primaryKey: 'name' }],
      });

      expect(codes(result)).toEqual(['wrong-trigger-primary-key']);
      expect(result.problems[0]!.message).toContain('"id"');
    });

    it('should report a table whose triggers send no notification on the channel', async () => {
      // The changelog trigger function of this suite sends none (notifyChannel: false)
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      await admin.unsafe(lilypadChangelogTriggerSql({ table: 'unwatched', primaryKey: 'id' }));
      try {
        const result = await check({
          tables: [{ table: 'unwatched', primaryKey: 'id' }],
          changelog: false,
          notifyChannel: 'cache_events',
        });

        expect(codes(result)).toEqual(['missing-notify-trigger']);
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should report a table whose triggers notify only some of INSERT, UPDATE and DELETE', async () => {
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      await admin`
        CREATE TRIGGER unwatched_cache_events AFTER UPDATE ON unwatched
        FOR EACH ROW EXECUTE FUNCTION notify_cache_events()
      `;
      try {
        const result = await check({
          tables: [{ table: 'unwatched', primaryKey: 'id' }],
          changelog: false,
          notifyChannel: 'cache_events',
        });

        expect(codes(result)).toEqual(['missing-notify-trigger']);
        expect(result.problems[0]!.message).toContain('only on UPDATE');
        expect(result.problems[0]!.message).toContain('not told about INSERT, DELETE');
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should accept notifications split across several triggers', async () => {
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      await admin`
        CREATE TRIGGER unwatched_insert AFTER INSERT ON unwatched
        FOR EACH ROW EXECUTE FUNCTION notify_cache_events()
      `;
      await admin`
        CREATE TRIGGER unwatched_update_delete AFTER UPDATE OR DELETE ON unwatched
        FOR EACH ROW EXECUTE FUNCTION notify_cache_events()
      `;
      await admin`
        CREATE TRIGGER unwatched_truncate AFTER TRUNCATE ON unwatched
        FOR EACH STATEMENT EXECUTE FUNCTION notify_cache_events()
      `;
      try {
        const result = await check({
          tables: [{ table: 'unwatched', primaryKey: 'id' }],
          changelog: false,
          notifyChannel: 'cache_events',
        });

        expect(result.ok).toBe(true);
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should report a missing changelog', async () => {
      const result = await check({
        tables: [users],
        changelog: { table: 'other_changes' },
      });

      expect(codes(result)).toEqual(['missing-changelog', 'missing-changelog-trigger']);
      expect(result.problems[0]!.fix).toContain('CREATE TABLE IF NOT EXISTS "other_changes"');
      expect(result.problems[1]!.fix).toContain('EXECUTE FUNCTION "other_changes_record"');
    });

    it('should report a changelog installed by version 1, and upgrade it', async () => {
      await admin.unsafe(lilypadChangelogSql({ table: 'legacy_changes', notifyChannel: false }));
      // What version 1 installed: no schema column, no version comment
      await admin`ALTER TABLE legacy_changes DROP COLUMN table_schema`;
      await admin`COMMENT ON FUNCTION legacy_changes_record() IS NULL`;
      try {
        const options = { tables: [], changelog: { table: 'legacy_changes' } };
        const result = await check(options);
        expect(codes(result)).toEqual(['outdated-changelog']);
        expect(result.problems[0]!.message).toContain('version 1');

        await admin.unsafe(result.problems[0]!.fix!);

        expect((await check(options)).ok).toBe(true);
      } finally {
        await admin`DROP TABLE legacy_changes`;
        await admin`DROP FUNCTION legacy_changes_record()`;
      }
    });
  });

  describe('tables of the same name in different schemas', () => {
    beforeAll(async () => {
      await admin`CREATE SCHEMA archive`;
      await admin`CREATE TABLE archive.users (id int PRIMARY KEY, name text NOT NULL)`;
      await admin.unsafe(lilypadChangelogTriggerSql({ table: 'archive.users', primaryKey: 'id' }));
      // A second changelog, whose trigger function also sends notifications on cache_events. Its
      // triggers are created by hand: the generated ones have the same names as the triggers above.
      await admin.unsafe(lilypadChangelogSql({ table: 'archive.changes' }));
      await admin.unsafe(`
        CREATE TRIGGER archive_users_notify_insert AFTER INSERT ON archive.users
          REFERENCING NEW TABLE AS lilypad_new
          FOR EACH STATEMENT EXECUTE FUNCTION archive_changes_record('id');
        CREATE TRIGGER archive_users_notify_update AFTER UPDATE ON archive.users
          REFERENCING OLD TABLE AS lilypad_old NEW TABLE AS lilypad_new
          FOR EACH STATEMENT EXECUTE FUNCTION archive_changes_record('id');
        CREATE TRIGGER archive_users_notify_delete AFTER DELETE ON archive.users
          REFERENCING OLD TABLE AS lilypad_old
          FOR EACH STATEMENT EXECUTE FUNCTION archive_changes_record('id');
      `);
    });

    afterAll(async () => {
      await admin`DROP SCHEMA archive CASCADE`;
      await admin`DROP FUNCTION archive_changes_record()`;
    });

    beforeEach(async () => {
      await admin`TRUNCATE archive.users, archive.changes`;
      await admin`TRUNCATE lilypad_cache_changes`;
    });

    it('should read the changes of the table of the given schema only', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      await admin`INSERT INTO archive.users (id, name) VALUES (7, 'old')`;
      const read = (tableName: string) =>
        readLilypadChanges(gate, { tableName, since: { lookback: 60_000 } });

      expect((await read('users')).changes.map((change) => change.rowId)).toEqual(['1']);
      expect((await read('public.users')).changes.map((change) => change.rowId)).toEqual(['1']);
      expect((await read('archive.users')).changes.map((change) => change.rowId)).toEqual(['7']);
    });

    it('should ignore the rows recorded without a schema by version 1', async () => {
      await admin`
        INSERT INTO lilypad_cache_changes (table_name, row_id, op) VALUES ('users', '9', 'UPDATE')
      `;

      const { changes } = await readLilypadChanges(gate, {
        tableName: 'archive.users',
        since: { lookback: 60_000 },
      });

      expect(changes).toEqual([]);
    });

    it('should notify each row of a statement recorded by a changelog that notifies', async () => {
      await admin`CREATE TABLE archive.notified (id int PRIMARY KEY)`;
      await admin.unsafe(
        lilypadChangelogTriggerSql({
          table: 'archive.notified',
          primaryKey: 'id',
          changelogTable: 'archive.changes',
        })
      );
      const received: unknown[] = [];
      await gate.addListener({
        channel: 'cache_events',
        callbackId: 'statement',
        callback: (payload) => {
          const parsed = JSON.parse(payload as string) as { table: string };
          if (parsed.table === 'notified') {
            received.push(parsed);
          }
        },
      });
      try {
        await admin`INSERT INTO archive.notified VALUES (1), (2)`;

        await vi.waitFor(() => expect(received).toHaveLength(2));
        expect(received).toEqual([
          expect.objectContaining({ schema: 'archive', id: '1', op: 'INSERT' }),
          expect.objectContaining({ schema: 'archive', id: '2', op: 'INSERT' }),
        ]);
        expect(
          (
            await checkLilypadSchema(gate, {
              tables: [{ table: 'archive.notified', primaryKey: 'id' }],
              changelog: { table: 'archive.changes' },
              notifyChannel: 'cache_events',
            })
          ).ok
        ).toBe(true);
      } finally {
        await gate.removeListener('cache_events', 'statement');
        await admin`DROP TABLE archive.notified`;
      }
    });

    it('should resolve the schema of each table', async () => {
      const result = await checkLilypadSchema(gate, {
        tables: [
          { table: 'users', primaryKey: 'id' },
          { table: 'archive.users', primaryKey: 'id' },
        ],
      });

      expect(result.ok).toBe(true);
      expect(result.tables).toEqual([
        { table: 'users', schema: 'public' },
        { table: 'archive.users', schema: 'archive' },
      ]);
    });

    it('should not apply to a LilypadDbCache the notifications of the other schema', async () => {
      const cache = await LilypadDbCache.create({
        ttl: 60_000,
        gate,
        table: usersSchema,
      });
      // Registered after the cache: when it sees a notification, the cache has applied it
      const seen: { schema?: string; op: string }[] = [];
      await gate.addListener({
        channel: 'cache_events',
        callbackId: 'archive-spy',
        callback: (payload) => void seen.push(JSON.parse(payload as string)),
      });
      try {
        const created = await cache.sqlCreate({ name: 'Ada', role: 'dev' });

        await admin`INSERT INTO archive.users (id, name) VALUES (1, 'old')`;
        await admin`DELETE FROM archive.users WHERE id = 1`;
        await vi.waitFor(() =>
          expect(seen).toContainEqual(expect.objectContaining({ schema: 'archive', op: 'DELETE' }))
        );

        expect(cache.get(1)).toEqual(created);
      } finally {
        await gate.removeListener('cache_events', 'archive-spy');
        await cache.dispose();
      }
    });
  });

  describe('singleton', () => {
    it('should create a new instance after the singleton is closed', async () => {
      const options = {
        connectionString: container.getConnectionUri(),
        listen: [],
        singleton: 'LilypadDbGate.integration-singleton',
      };
      const first = await LilypadDbGate.create(options);

      expect(await LilypadDbGate.create(options)).toBe(first);

      await first.close();
      const second = await LilypadDbGate.create(options);

      expect(second).not.toBe(first);
      await second.close();
    });
  });

  describe('with LilypadDbCache', () => {
    it('should keep the cache in sync through cache_events notifications', async () => {
      const cache = await LilypadDbCache.create({
        ttl: 60000,
        gate,
        table: usersSchema,
      });
      const created = await cache.sqlCreate({ name: 'Ada', role: 'dev' });
      expect(created?.id).toBe(1);

      await admin`UPDATE users SET role = 'admin' WHERE id = 1`;
      await vi.waitFor(() => expect(cache.get(1)).toEqual({ id: 1, name: 'Ada', role: 'admin' }));
      expect(cache.peek(1).type).toBe('hit');

      await admin`DELETE FROM users WHERE id = 1`;
      await vi.waitFor(() => expect(cache.get(1)).toBeNull());

      await admin`INSERT INTO users (name) VALUES ('Grace')`;
      expect((await cache.getAll()).size).toBe(1);
      await admin`TRUNCATE users`;
      await vi.waitFor(async () => expect((await cache.getAll()).size).toBe(0));

      await cache.dispose();
    });
  });

  describe('writes and notifications of large statements', () => {
    it('should leave the primary key out of the SET of an update', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      await admin`CREATE TABLE primary_key_updates (at timestamptz DEFAULT now())`;
      await admin`
        CREATE FUNCTION record_primary_key_update() RETURNS trigger AS $$
        BEGIN INSERT INTO primary_key_updates DEFAULT VALUES; RETURN NULL; END;
        $$ LANGUAGE plpgsql
      `;
      await admin`
        CREATE TRIGGER users_primary_key_update AFTER UPDATE OF id ON users
        FOR EACH ROW EXECUTE FUNCTION record_primary_key_update()
      `;
      try {
        const nonGenerated = usersTable({ generatedPrimaryKey: false });
        await gate.table(nonGenerated).update({ id: 1, name: 'Ada', role: 'admin' });

        // UPDATE OF id fires when id is in the SET list, even with the same value
        expect(await admin`SELECT * FROM primary_key_updates`).toHaveLength(0);
        await expect(gate.table(nonGenerated).update({ id: 1 })).rejects.toThrow(
          LilypadDbEmptyWriteError
        );
      } finally {
        await admin`DROP TRIGGER users_primary_key_update ON users`;
        await admin`DROP FUNCTION record_primary_key_update()`;
        await admin`DROP TABLE primary_key_updates`;
      }
    });

    it('should send one BULK notification for a statement above the threshold', async () => {
      await admin.unsafe(
        lilypadChangelogSql({
          table: 'bulk_changes',
          notifyChannel: 'bulk_events',
          notifyBulkThreshold: 2,
        })
      );
      await admin`CREATE TABLE bulk_items (id int PRIMARY KEY)`;
      await admin.unsafe(
        lilypadChangelogTriggerSql({
          table: 'bulk_items',
          primaryKey: 'id',
          changelogTable: 'bulk_changes',
        })
      );
      const payloads: Record<string, unknown>[] = [];
      const listener = await admin.listen('bulk_events', (payload) =>
        payloads.push(JSON.parse(payload) as Record<string, unknown>)
      );
      try {
        await admin`INSERT INTO bulk_items SELECT generate_series(1, 2)`;
        await admin`INSERT INTO bulk_items SELECT generate_series(3, 5)`;

        await vi.waitFor(() => expect(payloads).toHaveLength(3));
        expect(payloads.map(({ op, id }) => [op, id])).toEqual([
          ['INSERT', '1'],
          ['INSERT', '2'],
          ['BULK', undefined],
        ]);
        expect(payloads[2]).toMatchObject({ schema: 'public', table: 'bulk_items' });
        // Every row is still recorded in the changelog
        const [recorded] = await admin`SELECT count(*)::int AS count FROM bulk_changes`;
        expect(recorded!.count).toBe(5);
      } finally {
        await listener.unlisten();
        await admin`DROP TABLE bulk_items`;
        await admin`DROP TABLE bulk_changes`;
        await admin`DROP FUNCTION bulk_changes_record()`;
      }
    });
  });

  describe('lilypad-doctor', () => {
    it('should check the tables of a config and the pruning of the changelog, with its own connection', async () => {
      const config = defineLilypadDb({
        changelog: { pruning: 'trigger' },
        tables: {
          users: { ...usersInput, sync: { strategy: 'changelog', pollInterval: 1000 } },
          missing: { tableName: 'no_such_table', primaryKey: 'id', cols: { id: {} } },
        },
      });

      const report = await runLilypadDoctor({
        connectionString: container.getConnectionUri(),
        config,
      });

      expect(report.ok).toBe(false);
      expect(report.config).toBe('default');
      expect(report.problems.map((problem) => problem.code)).toContain('missing-table');
      expect(report.tables).toEqual([
        { table: 'public.users', schema: 'public' },
        { table: 'public.no_such_table', schema: null },
      ]);
      expect(report.text).toContain(
        'lilypad-doctor (config "default"): the database is not set up.'
      );
      expect(() => report.assertOk()).toThrow(LilypadSchemaCheckError);
    });
  });

  describe('the shape of the tables', () => {
    type Team = { id: number; slug: string; name: string };
    type Member = {
      id: string;
      teamId: number;
      email: string;
      score: number;
      tags: string[];
      joinedAt: Date;
      managerId: string | null;
    };
    const shapeDb = (strict = false) =>
      defineLilypadDb({
        strict,
        tables: {
          teams: defineLilypadTable<Team, 'id'>({
            tableName: 'shape_teams',
            primaryKey: 'id',
            generatedPrimaryKey: true,
            cols: {
              id: { type: 'number', pgType: 'int4' },
              slug: { type: 'string', pgType: 'varchar(64)', nullable: false, unique: true },
              name: { type: 'string', pgType: 'text', nullable: false },
            },
            sync: { strategy: 'none' },
          }),
          members: defineLilypadTable<Member, 'id'>({
            tableName: 'shape_members',
            primaryKey: 'id',
            generatedPrimaryKey: true,
            cols: {
              id: { type: 'string', pgType: 'uuid', default: { sql: 'gen_random_uuid()' } },
              teamId: {
                type: 'number',
                pgType: 'int4',
                nullable: false,
                references: { table: 'shape_teams', onDelete: 'cascade' },
              },
              email: { type: 'string', pgType: 'text', nullable: false },
              score: { type: 'number', pgType: 'int4', nullable: false, default: { sql: '0' } },
              tags: { type: 'array', pgType: 'text[]', nullable: false, default: { sql: "'{}'" } },
              joinedAt: { type: 'date', pgType: 'timestamptz', default: { sql: 'now()' } },
              managerId: { type: 'string', pgType: 'uuid', nullable: true },
            },
            unique: [{ columns: ['teamId', 'email'] }],
            foreignKeys: [
              {
                name: 'shape_members_manager_fkey',
                columns: ['managerId'],
                references: { table: 'shape_members', onDelete: 'set null' },
              },
            ],
            indexes: [{ columns: ['teamId', 'score'] }, { columns: ['tags'], using: 'gin' }],
            checks: [{ name: 'shape_members_score_check', expression: 'score >= 0' }],
            sync: { strategy: 'listen' },
          }),
        },
      });
    const check = (strict = false) =>
      checkLilypadSchema(gate, lilypadSchemaCheckOptions(shapeDb(strict)));
    const codes = (result: Awaited<ReturnType<typeof check>>) =>
      result.problems.map((problem) => `${problem.table ?? ''}:${problem.code}`);
    /** Runs the SQL that fixes the problems, as `lilypad-doctor --sql` prints it. */
    const applyFixes = async (result: Awaited<ReturnType<typeof check>>) => {
      const fixes = [
        ...new Set(result.problems.flatMap((problem) => (problem.fix ? [problem.fix] : []))),
      ];
      await admin.unsafe(fixes.join('\n'));
    };

    afterEach(async () => {
      await admin`DROP TABLE IF EXISTS shape_members, shape_teams`;
    });

    it('should create the missing tables with the SQL of the fixes, and find nothing after', async () => {
      const missing = await check();
      expect(codes(missing)).toEqual([
        'public.shape_teams:missing-table',
        'public.shape_members:missing-table',
        'public.shape_members:missing-foreign-key',
        'public.shape_members:missing-foreign-key',
      ]);

      await applyFixes(missing);

      expect(await check()).toEqual({
        ok: true,
        problems: [],
        tables: [
          { table: 'public.shape_teams', schema: 'public' },
          { table: 'public.shape_members', schema: 'public' },
        ],
      });
      // The table works as described: generated keys, defaults, the foreign key
      const teams = gate.table(shapeDb().tables.teams);
      const { row: team } = await teams.insert({ slug: 'core', name: 'Core' });
      const { row: member } = await gate
        .table(shapeDb().tables.members)
        .insert({ teamId: team!.id, email: 'ada@example.com' } as Member);
      expect(member).toMatchObject({ teamId: team!.id, score: 0, tags: [], managerId: null });
      expect(member!.joinedAt).toBeInstanceOf(Date);
    });

    it('should report the columns, keys, foreign keys, indexes and checks that differ', async () => {
      await admin`
        CREATE TABLE shape_teams (id serial PRIMARY KEY, slug varchar(32), name text NOT NULL)
      `;
      await admin`
        CREATE TABLE shape_members (
          id uuid PRIMARY KEY,
          "teamId" int NOT NULL REFERENCES shape_teams (id),
          email text NOT NULL,
          score int NOT NULL DEFAULT 0,
          tags text[] NOT NULL DEFAULT '{}',
          "managerId" uuid,
          tenant text NOT NULL
        )
      `;
      await admin`CREATE INDEX ON shape_members ("teamId")`;

      const result = await check();

      expect(result.ok).toBe(false);
      expect(result.problems.map((problem) => [problem.code, problem.message])).toEqual([
        [
          'column-type-mismatch',
          'The column "slug" of "public.shape_teams" is character varying(32), not character varying(64).',
        ],
        [
          'column-nullability-mismatch',
          'The column "slug" of "public.shape_teams" accepts NULL, but is declared not nullable.',
        ],
        [
          'missing-unique-key',
          'The columns (slug) of "public.shape_teams" are not unique together: no unique constraint or index covers exactly them.',
        ],
        [
          'missing-column-default',
          'The primary key "id" of "public.shape_members" is declared generated (generatedPrimaryKey), but the database does not generate it.',
        ],
        ['missing-column', 'The column "joinedAt" of "public.shape_members" does not exist.'],
        [
          'undeclared-required-column',
          'The column "tenant" of "public.shape_members" is NOT NULL without a default, and is not in `cols`: inserts through the library fail.',
        ],
        [
          'missing-unique-key',
          'The columns (teamId, email) of "public.shape_members" are not unique together: no unique constraint or index covers exactly them.',
        ],
        [
          'foreign-key-mismatch',
          'The foreign key (teamId) → public.shape_teams (id) of "public.shape_members" is ON DELETE NO ACTION ON UPDATE NO ACTION, not ON DELETE CASCADE ON UPDATE NO ACTION.',
        ],
        [
          'missing-index',
          'The btree index on (teamId, score) of "public.shape_members" does not exist.',
        ],
        ['missing-index', 'The gin index on (tags) of "public.shape_members" does not exist.'],
        [
          'missing-check',
          'The check "shape_members_score_check" of "public.shape_members" does not exist.',
        ],
        [
          'missing-notify-trigger',
          'No trigger of "public.shape_members" sends notifications on the "cache_events" channel: the cache is not told about changes made elsewhere.',
        ],
        [
          'missing-foreign-key',
          'The foreign key (managerId) → public.shape_members (id) of "public.shape_members" does not exist.',
        ],
      ]);

      // The fixes bring the tables to the description, apart from the column it does not know
      await admin`ALTER TABLE shape_members DROP COLUMN tenant`;
      await applyFixes(await check());
      expect(codes(await check())).toEqual([]);
      // With strict, the index of the database that the description lacks
      expect(codes(await check(true))).toEqual(['public.shape_members:undeclared-index']);
    });

    it('should judge the columns of a domain by its base type, through nested domains', async () => {
      await admin.unsafe(`
        CREATE DOMAIN shape_big_id AS int8 CHECK (VALUE > 0);
        CREATE DOMAIN shape_small_id AS shape_big_id;
        CREATE DOMAIN shape_count AS int4;
        CREATE TABLE shape_domains (id shape_small_id PRIMARY KEY, n shape_count, at timetz);
      `);
      type Row = { id: string; n: string; at: string };
      const domainsDb = defineLilypadDb({
        tables: {
          domains: defineLilypadTable<Row, 'id'>({
            tableName: 'shape_domains',
            primaryKey: 'id',
            cols: { id: { type: 'string' }, n: { type: 'string' }, at: { type: 'string' } },
            sync: { strategy: 'none' },
          }),
        },
      });

      try {
        const result = await checkLilypadSchema(gate, lilypadSchemaCheckOptions(domainsDb));

        expect(result.problems.map((problem) => problem.message)).toEqual([
          'The column "n" of "public.shape_domains" is shape_count, declared as string: postgres.js reads it as number (declare number).',
        ]);
        // What postgres.js returns indeed
        await admin`INSERT INTO shape_domains VALUES (1, 2, '12:00+00')`;
        const [row] = await admin`SELECT * FROM shape_domains`;
        expect([typeof row!.id, typeof row!.n, typeof row!.at]).toEqual([
          'string',
          'number',
          'string',
        ]);
      } finally {
        await admin.unsafe(
          'DROP TABLE shape_domains; DROP DOMAIN shape_small_id; DROP DOMAIN shape_big_id; DROP DOMAIN shape_count;'
        );
      }
    });
  });
});
