import { describe, it, expect, beforeAll, afterAll, beforeEach, vi } from 'vitest';
import { PostgreSqlContainer, type StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import postgres from 'postgres';
import { LilypadDbGate, LilypadDbNotFoundError, type LilypadDbSchema } from './LilypadDbGate';
import { LilypadDbCache } from '@/cache/LilypadDbCache';
import {
  lilypadChangelogPruneScheduleSql,
  lilypadChangelogSql,
  lilypadChangelogTriggerSql,
  pruneLilypadChangelog,
  readLilypadChanges,
  readLilypadChangesBatch,
} from './LilypadChangelog';
import { checkLilypadSchema } from './LilypadSchemaCheck';
import type { LilypadLoggerType } from '@/logger/LilypadLogger';

type User = { id: number; name: string; role: string };

const usersSchema: LilypadDbSchema<User, 'id'> = {
  tableName: 'users',
  primaryKey: 'id',
  generatedPrimaryKey: true,
  cols: { id: { type: 'number' }, name: { type: 'string' }, role: { type: 'string' } },
};

const createMockLogger = () =>
  ({
    error: vi.fn(),
    warn: vi.fn(),
    info: vi.fn(),
    debug: vi.fn(),
  }) as unknown as LilypadLoggerType<'error' | 'warn' | 'info' | 'debug'>;

describe('LilypadDbGate (integration)', () => {
  let container: StartedPostgreSqlContainer;
  let admin: postgres.Sql;
  let gate: LilypadDbGate;

  beforeAll(async () => {
    container = await new PostgreSqlContainer('postgres:16-alpine').start();
    admin = postgres(container.getConnectionUri(), { onnotice: () => {} });
    await admin`
      CREATE TABLE users (
        id serial PRIMARY KEY,
        name text NOT NULL,
        role text NOT NULL DEFAULT 'user',
        is_admin boolean NOT NULL DEFAULT false
      )
    `;
    // The notification contract expected by LilypadDbCache's default listener
    await admin`
      CREATE FUNCTION notify_cache_events() RETURNS trigger AS $$
      BEGIN
        IF TG_OP = 'TRUNCATE' THEN
          PERFORM pg_notify('cache_events', json_build_object(
            'table', TG_TABLE_NAME, 'op', TG_OP
          )::text);
          RETURN NULL;
        END IF;
        PERFORM pg_notify('cache_events', json_build_object(
          'table', TG_TABLE_NAME,
          'id', COALESCE(NEW.id, OLD.id),
          'op', TG_OP
        )::text);
        RETURN NULL;
      END;
      $$ LANGUAGE plpgsql
    `;
    await admin`
      CREATE TRIGGER users_cache_events AFTER INSERT OR UPDATE OR DELETE ON users
      FOR EACH ROW EXECUTE FUNCTION notify_cache_events()
    `;
    await admin`
      CREATE TRIGGER users_cache_events_truncate AFTER TRUNCATE ON users
      FOR EACH STATEMENT EXECUTE FUNCTION notify_cache_events()
    `;
    await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
    await admin.unsafe(lilypadChangelogTriggerSql({ table: 'users', primaryKey: 'id' }));
    gate = await LilypadDbGate.create({
      connectionString: container.getConnectionUri(),
      listen: [],
    });
  });

  afterAll(async () => {
    await gate?.close();
    await admin?.end();
    await container?.stop();
  });

  beforeEach(async () => {
    // The changelog records the TRUNCATE of users: it is emptied afterwards
    await admin`TRUNCATE users RESTART IDENTITY`;
    await admin`TRUNCATE lilypad_cache_changes RESTART IDENTITY`;
  });

  describe('CRUD', () => {
    it('should insert a row and return it with the generated primary key', async () => {
      const { row: created } = await gate.insertToTable(usersSchema, {
        name: 'Ada',
        role: 'dev',
      } as User);

      expect(created).toEqual({ id: 1, name: 'Ada', role: 'dev' });
    });

    it('should ignore the primary key of the data when it is generated by the database', async () => {
      const { row: created } = await gate.insertToTable(usersSchema, {
        id: 999,
        name: 'Ada',
        role: 'dev',
      });

      expect(created?.id).toBe(1);
    });

    it('should require the primary key when it is not generated by the database', async () => {
      const schema = { ...usersSchema, generatedPrimaryKey: false };

      await expect(
        gate.insertToTable(schema, { name: 'Ada', role: 'dev' } as User)
      ).rejects.toThrow('Primary key "id" is missing in the insert data for table "users".');
    });

    it('should never write properties that are not schema columns', async () => {
      const payload = { name: 'Mallory', role: 'user', is_admin: true } as unknown as User;

      await gate.insertToTable(usersSchema, payload);
      await gate.updateToTable(usersSchema, { ...payload, id: 1 });

      const [row] = await admin`SELECT is_admin FROM users WHERE id = 1`;
      expect(row!.is_admin).toBe(false);
    });

    it('should select only the schema columns', async () => {
      await admin`INSERT INTO users (name, role, is_admin) VALUES ('Ada', 'dev', true)`;

      expect(await gate.selectAllFromTable(usersSchema)).toEqual([
        { id: 1, name: 'Ada', role: 'dev' },
      ]);
      expect(await gate.selectFromTableByPrimaryKey(usersSchema, 1)).toEqual({
        id: 1,
        name: 'Ada',
        role: 'dev',
      });
      expect(await gate.selectFromTableByPrimaryKey(usersSchema, 2)).toBeNull();
    });

    it('should pass the whole row to the selectSanitizationFn', async () => {
      await admin`INSERT INTO users (name, role, is_admin) VALUES ('Ada', 'dev', true)`;
      const selectSanitizationFn = vi.fn((row: unknown) => row as User);

      await gate.selectAllFromTable({ ...usersSchema, selectSanitizationFn });

      expect(selectSanitizationFn).toHaveBeenCalledWith(
        expect.objectContaining({ is_admin: true })
      );
    });

    it('should select the rows of several primary keys in one query', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada'), ('Grace'), ('Linus')`;

      const rows = await gate.selectFromTableByPrimaryKeys(usersSchema, [1, 3, 42]);

      expect(rows.map((row) => row.name).sort()).toEqual(['Ada', 'Linus']);
      expect(await gate.selectFromTableByPrimaryKeys(usersSchema, [])).toEqual([]);
    });

    it('should update a row and return it', async () => {
      await gate.insertToTable(usersSchema, { name: 'Ada', role: 'dev' } as User);

      const { row: updated } = await gate.updateToTable(usersSchema, {
        id: 1,
        name: 'Ada',
        role: 'admin',
      });

      expect(updated).toEqual({ id: 1, name: 'Ada', role: 'admin' });
    });

    it('should throw a LilypadDbNotFoundError when updating a row that does not exist', async () => {
      const updating = gate.updateToTable(usersSchema, { id: 42, name: 'Ghost', role: 'user' });

      await expect(updating).rejects.toThrow(
        'No row with primary key "42" found in table "users".'
      );
      await expect(updating).rejects.toBeInstanceOf(LilypadDbNotFoundError);
      await expect(updating).rejects.toMatchObject({ tableName: 'users', primaryKeyValue: 42 });
    });

    it('should require the primary key to update, even when it is generated', async () => {
      await expect(
        gate.updateToTable(usersSchema, { name: 'Ada', role: 'dev' } as User)
      ).rejects.toThrow('Primary key "id" is missing in the update data for table "users".');
    });

    it('should delete a row', async () => {
      await gate.insertToTable(usersSchema, { name: 'Ada', role: 'dev' } as User);

      const deleted = await gate.deleteFromTable(usersSchema, 1);

      expect(deleted).toEqual({ deleted: true, xid: expect.any(BigInt) as bigint });
      expect(await gate.selectAllFromTable(usersSchema)).toEqual([]);
      expect(await gate.deleteFromTable(usersSchema, 1)).toEqual({ deleted: false });
    });

    it('should write the result of the writeSanitizationFn, which can remove properties', async () => {
      const schema: LilypadDbSchema<User, 'id'> = {
        ...usersSchema,
        writeSanitizationFn: ({ role: _role, ...rest }) => rest,
      };

      const { row: created } = await gate.insertToTable(schema, { name: 'Mallory', role: 'admin' });

      expect(created?.role).toBe('user');
    });

    it('should skip undefined values instead of failing', async () => {
      // e.g. an optional field of a request body that was not sent
      const data = { name: 'Ada', role: undefined as unknown as string };

      const { row: created } = await gate.insertToTable(usersSchema, data);

      expect(created).toEqual({ id: 1, name: 'Ada', role: 'user' });
    });

    it('should update only the columns present in the data', async () => {
      await gate.insertToTable(usersSchema, { name: 'Ada', role: 'dev' });

      const { row: updated } = await gate.updateToTable(usersSchema, { id: 1, role: 'admin' });

      expect(updated).toEqual({ id: 1, name: 'Ada', role: 'admin' });
    });

    it('should return only the schema columns of a written row, unless a selectSanitizationFn reads it', async () => {
      const seen: unknown[] = [];
      const schema: LilypadDbSchema<User, 'id'> = {
        ...usersSchema,
        selectSanitizationFn: (row) => {
          seen.push(row);
          return row as User;
        },
      };

      const { row: plain } = await gate.insertToTable(usersSchema, { name: 'Ada', role: 'dev' });
      await gate.insertToTable(schema, { name: 'Grace', role: 'dev' });

      expect(Object.keys(plain!).sort()).toEqual(['id', 'name', 'role']);
      // The selectSanitizationFn receives the whole row, as when it selects
      expect(seen[0]).toMatchObject({ is_admin: false });
    });

    it('should select tables larger than one cursor batch', async () => {
      await admin`INSERT INTO users (name) SELECT 'user' || i FROM generate_series(1, 2500) AS i`;

      expect(await gate.selectAllFromTable(usersSchema)).toHaveLength(2500);
    });

    it('should stop reading a table once its signal is aborted', async () => {
      await admin`INSERT INTO users (name) SELECT 'user' || i FROM generate_series(1, 2500) AS i`;
      const controller = new AbortController();

      const reading = gate.selectAllFromTable(usersSchema, { signal: controller.signal });
      controller.abort(new Error('timed out'));

      await expect(reading).rejects.toThrow('timed out');
      await expect(
        gate.selectAllFromTable(usersSchema, { signal: controller.signal })
      ).rejects.toThrow('timed out');
      // The cursor was closed: the connection is usable again
      expect(await gate.selectAllFromTable(usersSchema)).toHaveLength(2500);
    });

    it('should cancel queries longer than statementTimeout on the server', async () => {
      const limitedGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        statementTimeout: 100,
      });

      await expect(limitedGate.sql`SELECT pg_sleep(1)`).rejects.toThrow('statement timeout');
      await limitedGate.close();
    });

    it('should escape table names', async () => {
      const schema = { ...usersSchema, tableName: 'users; DROP TABLE users; --' };

      await expect(gate.selectAllFromTable(schema)).rejects.toThrow('does not exist');
      const [check] = await admin`SELECT to_regclass('users') IS NOT NULL AS exists`;
      expect(check?.exists).toBe(true);
    });
  });

  describe('listeners', () => {
    it('should deliver notifications to every callback of the channel', async () => {
      const first = vi.fn();
      const second = vi.fn();
      await gate.addListener({ channel: 'test_channel', callbackId: 'first', callback: first });
      await gate.addListener({ channel: 'test_channel', callbackId: 'second', callback: second });

      await admin.notify('test_channel', 'hello');

      await vi.waitFor(() => {
        expect(first).toHaveBeenCalledWith('hello');
        expect(second).toHaveBeenCalledWith('hello');
      });
      await gate.removeListener('test_channel', 'first');
      await gate.removeListener('test_channel', 'second');
    });

    it('should log a rejected async callback without affecting the others', async () => {
      const logger = createMockLogger();
      const loggedGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        logger,
        listen: [
          {
            channel: 'failing_channel',
            callbackId: 'failing',
            callback: async () => {
              throw new Error('callback failed');
            },
          },
        ],
      });
      const healthy = vi.fn();
      await loggedGate.addListener({
        channel: 'failing_channel',
        callbackId: 'healthy',
        callback: healthy,
      });

      await admin.notify('failing_channel', 'payload');

      await vi.waitFor(() => {
        expect(healthy).toHaveBeenCalledWith('payload');
        expect(logger.error).toHaveBeenCalledWith(
          loggedGate.id,
          expect.stringContaining('"failing"'),
          expect.any(Error)
        );
      });
      await loggedGate.close();
    });

    it('should stop delivering notifications to removed callbacks', async () => {
      const removed = vi.fn();
      const kept = vi.fn();
      await gate.addListener({
        channel: 'removal_channel',
        callbackId: 'removed',
        callback: removed,
      });
      await gate.addListener({ channel: 'removal_channel', callbackId: 'kept', callback: kept });

      expect(await gate.removeListener('removal_channel', 'removed')).toBe(true);
      await admin.notify('removal_channel', 'payload');

      await vi.waitFor(() => expect(kept).toHaveBeenCalled());
      expect(removed).not.toHaveBeenCalled();
      await gate.removeListener('removal_channel', 'kept');
    });

    it('should share a single LISTEN between concurrent addListener calls', async () => {
      const first = vi.fn();
      const second = vi.fn();

      await Promise.all([
        gate.addListener({ channel: 'concurrent_channel', callbackId: 'first', callback: first }),
        gate.addListener({ channel: 'concurrent_channel', callbackId: 'second', callback: second }),
      ]);
      await admin.notify('concurrent_channel', 'payload');

      await vi.waitFor(() => {
        expect(first).toHaveBeenCalledOnce();
        expect(second).toHaveBeenCalledOnce();
      });
      await gate.removeListener('concurrent_channel', 'first');
      await gate.removeListener('concurrent_channel', 'second');
    });
  });

  describe('listener lifecycle', () => {
    it('should call onReconnect once the listener connection is re-established', async () => {
      const callback = vi.fn();
      const onReconnect = vi.fn();
      const reconnectingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listen: [{ channel: 'reconnect_channel', callbackId: 'cb', callback, onReconnect }],
        listenHeartbeat: false,
      });
      expect(onReconnect).not.toHaveBeenCalled();

      await admin`
        SELECT pg_terminate_backend(pid) FROM pg_stat_activity
        WHERE query ILIKE 'listen%reconnect_channel%'
      `;

      await vi.waitFor(() => expect(onReconnect).toHaveBeenCalledOnce(), { timeout: 10000 });
      await admin.notify('reconnect_channel', 'after');
      await vi.waitFor(() => expect(callback).toHaveBeenCalledWith('after'));
      await reconnectingGate.close();
    });

    it('should remove a callback whose LISTEN is still pending', async () => {
      const callback = vi.fn();
      const adding = gate.addListener({ channel: 'pending_channel', callbackId: 'cb', callback });

      expect(await gate.removeListener('pending_channel', 'cb')).toBe(true);
      await adding;
      await admin.notify('pending_channel', 'payload');
      await new Promise((resolve) => setTimeout(resolve, 200));

      expect(callback).not.toHaveBeenCalled();
    });

    it('should report the LISTEN connection as healthy while heartbeats come back', async () => {
      const beatingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listenHeartbeat: 100,
      });
      expect(beatingGate.isListenHealthy()).toBe(false);

      await beatingGate.addListener({
        channel: 'beating_channel',
        callbackId: 'cb',
        callback: vi.fn(),
      });
      await new Promise((resolve) => setTimeout(resolve, 400));
      expect(beatingGate.isListenHealthy()).toBe(true);

      await beatingGate.removeListener('beating_channel', 'cb');
      expect(beatingGate.isListenHealthy()).toBe(false);
      await beatingGate.close();
    });

    it('should report the LISTEN connection as unhealthy when heartbeats stop coming back', async () => {
      const beatingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listenHeartbeat: 100,
        listen: [{ channel: 'silent_channel', callbackId: 'cb', callback: vi.fn() }],
      });
      // The heartbeats are sent to a channel nobody listens to any more
      Object.assign(beatingGate, { heartbeatChannel: 'lilypad_heartbeat_elsewhere' });

      await vi.waitFor(() => expect(beatingGate.isListenHealthy()).toBe(false), { timeout: 2000 });
      await beatingGate.close();
    });

    it('should close a gate that still has active listeners', async () => {
      const closingGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
        listen: [{ channel: 'closing_channel', callbackId: 'cb', callback: vi.fn() }],
      });

      await expect(closingGate.close()).resolves.toBeUndefined();
    });
  });

  describe('changelog', () => {
    const readAll = () =>
      readLilypadChanges(gate, { tableName: 'users', since: { lookback: 60_000 } });

    it('should record inserts, updates, deletes and primary key changes', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      await admin`UPDATE users SET role = 'admin' WHERE id = 1`;
      await admin`UPDATE users SET id = 2 WHERE id = 1`;
      await admin`DELETE FROM users WHERE id = 2`;

      const { changes } = await readAll();

      expect(changes.map(({ op, rowId }) => `${op}:${rowId}`)).toEqual([
        'INSERT:1',
        'UPDATE:1',
        'DELETE:1', // the primary key change removes the old key...
        'UPDATE:2', // ...and updates the new one
        'DELETE:2',
      ]);
    });

    it('should record every row of a statement, with the primary key changes', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada'), ('Grace'), ('Alan')`;
      await admin`UPDATE users SET id = id + 10 WHERE id <= 2`;
      await admin`UPDATE users SET role = 'admin'`;
      await admin`DELETE FROM users WHERE id > 10`;

      const { changes } = await readAll();

      expect(changes.map(({ op, rowId }) => `${op}:${rowId}`)).toEqual([
        'INSERT:1',
        'INSERT:2',
        'INSERT:3',
        'DELETE:1', // no row has the keys 1 and 2 any more...
        'DELETE:2',
        'UPDATE:11', // ...and the new keys are updated
        'UPDATE:12',
        'UPDATE:3',
        'UPDATE:11',
        'UPDATE:12',
        'DELETE:11',
        'DELETE:12',
      ]);
      expect(new Set(changes.slice(0, 3).map((change) => change.xid)).size).toBe(1);
    });

    it('should record nothing for a statement that changes no row', async () => {
      await admin`UPDATE users SET role = 'admin' WHERE id = 42`;

      expect((await readAll()).changes).toEqual([]);
    });

    it('should record TRUNCATE', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      await admin`TRUNCATE users`;

      const { changes } = await readAll();

      expect(changes.map(({ op, rowId }) => `${op}:${rowId}`)).toEqual([
        'INSERT:1',
        'TRUNCATE:null',
      ]);
    });

    it('should return with each write the transaction id that the changelog records', async () => {
      const created = await gate.insertToTable(usersSchema, { name: 'Ada', role: 'dev' });
      const updated = await gate.updateToTable(usersSchema, { id: 1, role: 'admin' });
      const deleted = await gate.deleteFromTable(usersSchema, 1);

      const { changes } = await readAll();

      expect(created.row).toEqual({ id: 1, name: 'Ada', role: 'dev' });
      expect(updated.row).toEqual({ id: 1, name: 'Ada', role: 'admin' });
      expect(changes.map((change) => change.xid)).toEqual([created.xid, updated.xid, deleted.xid]);
      expect(await gate.deleteFromTable(usersSchema, 1)).toEqual({ deleted: false });
    });

    it('should not miss a transaction that commits after a later one', async () => {
      const slow = await admin.reserve();
      try {
        await slow`BEGIN`;
        await slow`INSERT INTO users (name) VALUES ('slow')`; // id 1, not committed yet
        await admin`INSERT INTO users (name) VALUES ('fast')`; // id 2, committed
        const first = await readAll();
        expect(first.changes.map((change) => change.rowId)).toEqual(['2']);

        await slow`COMMIT`;
        const next = await readLilypadChanges(gate, {
          tableName: 'users',
          since: { cursor: first.cursor },
        });

        // The slow transaction is returned once it commits, and the fast one is not returned again
        expect(next.changes.map((change) => change.rowId)).toEqual(['1']);
      } finally {
        slow.release();
      }
    });

    it('should not return again the changes committed while a long transaction runs', async () => {
      const long = await admin.reserve();
      try {
        await long`BEGIN`;
        // A transaction id, as any writing transaction has (e.g. a long migration)
        await long`SELECT pg_current_xact_id()`;
        await admin`INSERT INTO users (name) VALUES ('first')`;
        const first = await readAll();
        expect(first.cursor.xip.length).toBeGreaterThan(0);

        await admin`INSERT INTO users (name) VALUES ('second')`;
        const second = await readLilypadChanges(gate, {
          tableName: 'users',
          since: { cursor: first.cursor },
        });
        const third = await readLilypadChanges(gate, {
          tableName: 'users',
          since: { cursor: second.cursor },
        });

        expect(second.changes.map((change) => change.rowId)).toEqual(['2']);
        expect(third.changes).toEqual([]);
        await long`ROLLBACK`;
      } finally {
        long.release();
      }
    });

    it('should read several requests in one query, each from its own cursor or lookback', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      const { cursor } = await readAll();
      await admin`INSERT INTO users (name) VALUES ('Grace')`;

      const { changes } = await readLilypadChangesBatch(gate, {
        requests: [
          { tableName: 'users', since: { lookback: 60_000 } },
          { tableName: 'users', since: { cursor } },
          { tableName: 'no_such_table', since: { lookback: 60_000 } },
        ],
      });

      expect(changes.map((list) => list.map((change) => change.rowId))).toEqual([
        ['1', '2'],
        ['2'],
        [],
      ]);
    });

    it('should read the changelog with the first query of a new gate', async () => {
      // postgres.js has not loaded the array types yet when it builds the first query
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      const coldGate = await LilypadDbGate.create({
        connectionString: container.getConnectionUri(),
      });

      try {
        const { changes } = await readLilypadChangesBatch(coldGate, {
          requests: [
            { tableName: 'users', since: { lookback: 60_000 } },
            { tableName: 'users', since: { cursor: { xmax: 1n, xip: [1n, 2n] } } },
            { tableName: 'no "such" \\ table', since: { lookback: 60_000 } },
          ],
        });

        expect(changes.map((list) => list.map((change) => change.rowId))).toEqual([
          ['1'],
          ['1'],
          [],
        ]);
      } finally {
        await coldGate.close();
      }
    });

    it('should delete the rows older than the retention', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;

      expect(await pruneLilypadChangelog(gate, { olderThan: 0 })).toBe(1);
      expect((await readAll()).changes).toEqual([]);
    });

    describe('pruning', () => {
      /** Records `count` changes, dated two hours ago. */
      const recordOldChanges = async (count: number) => {
        await admin`INSERT INTO users (name) SELECT 'old' FROM generate_series(1, ${count})`;
        await admin`UPDATE lilypad_cache_changes SET changed_at = now() - interval '2 hours'`;
      };
      const countChanges = async () => {
        const [row] = await admin`
          SELECT count(*) FILTER (WHERE changed_at < now() - interval '1 hour')::int AS old,
            count(*) FILTER (WHERE changed_at >= now() - interval '1 hour')::int AS recent
          FROM lilypad_cache_changes
        `;
        return row as { old: number; recent: number };
      };

      describe('from the trigger', () => {
        beforeAll(async () => {
          await admin.unsafe(
            lilypadChangelogSql({
              notifyChannel: false,
              prune: { olderThan: 60 * 60_000, every: 1, batchSize: 2 },
            })
          );
          // A role that can write the cached table and record its changes, but not delete them
          await admin.unsafe(`
            CREATE ROLE lilypad_writer;
            GRANT INSERT, UPDATE ON users TO lilypad_writer;
            GRANT USAGE ON SEQUENCE users_id_seq TO lilypad_writer;
            GRANT INSERT ON lilypad_cache_changes TO lilypad_writer;
            GRANT USAGE ON SEQUENCE lilypad_cache_changes_id_seq TO lilypad_writer;
          `);
        });

        afterAll(async () => {
          await admin.unsafe(`
            DROP OWNED BY lilypad_writer;
            DROP ROLE lilypad_writer;
          `);
          await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
        });

        it('should delete a batch of old rows with a write, even without the DELETE privilege', async () => {
          await recordOldChanges(3);

          await admin.begin(async (tx) => {
            await tx`SET LOCAL ROLE lilypad_writer`;
            await tx`INSERT INTO users (name) VALUES ('Ada')`;
          });

          expect(await countChanges()).toEqual({ old: 1, recent: 1 });
        });

        it('should not prune in a transaction stricter than READ COMMITTED', async () => {
          await recordOldChanges(3);

          await admin.begin('isolation level repeatable read', async (tx) => {
            await tx`INSERT INTO users (name) VALUES ('Ada')`;
          });

          expect(await countChanges()).toEqual({ old: 3, recent: 1 });
        });

        it('should not prune any more once installed without the option', async () => {
          await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
          try {
            await recordOldChanges(3);
            await admin`INSERT INTO users (name) VALUES ('Ada')`;

            expect(await countChanges()).toEqual({ old: 3, recent: 1 });
            const [row] = await admin`
              SELECT to_regprocedure('lilypad_cache_changes_prune()') IS NULL AS dropped
            `;
            expect(row!.dropped).toBe(true);
          } finally {
            await admin.unsafe(
              lilypadChangelogSql({
                notifyChannel: false,
                prune: { olderThan: 60 * 60_000, every: 1, batchSize: 2 },
              })
            );
          }
        });

        it('should keep the pruning in the fix of an outdated changelog', async () => {
          await admin`COMMENT ON FUNCTION lilypad_cache_changes_record() IS 'lilypad-changelog:3'`;
          try {
            const result = await checkLilypadSchema(gate, { tables: [] });

            expect(result.problems[0]!.fix).toBe(
              lilypadChangelogSql({
                notifyChannel: false,
                prune: { olderThan: 60 * 60_000, every: 1, batchSize: 2 },
              })
            );
          } finally {
            await admin`COMMENT ON FUNCTION lilypad_cache_changes_record() IS 'lilypad-changelog:4'`;
          }
        });
      });

      it('should schedule a pg_cron job that deletes the old rows', async () => {
        // pg_cron is not in the image: a stand-in cron.schedule records the job
        await admin.unsafe(`
          CREATE SCHEMA cron;
          CREATE TABLE cron.job (jobname text PRIMARY KEY, schedule text, command text);
          CREATE FUNCTION cron.schedule(job_name text, schedule text, command text) RETURNS bigint AS $$
            INSERT INTO cron.job VALUES (job_name, schedule, command)
            ON CONFLICT (jobname) DO UPDATE SET schedule = excluded.schedule, command = excluded.command;
            SELECT 1::bigint;
          $$ LANGUAGE sql;
        `);
        try {
          await admin.unsafe(lilypadChangelogPruneScheduleSql({ olderThan: 60 * 60_000 }));
          await admin.unsafe(
            lilypadChangelogPruneScheduleSql({ olderThan: 60 * 60_000, schedule: '0 * * * *' })
          );
          const jobs = await admin`SELECT jobname, schedule, command FROM cron.job`;
          expect(jobs).toEqual([
            {
              jobname: 'lilypad_cache_changes_prune',
              schedule: '0 * * * *',
              command:
                'DELETE FROM public.lilypad_cache_changes WHERE changed_at < clock_timestamp() - make_interval(secs => 3600)',
            },
          ]);

          await recordOldChanges(3);
          await admin`INSERT INTO users (name) VALUES ('Ada')`;
          // The job runs in its own session, with the search_path of its role
          await admin.begin(async (tx) => {
            await tx`SET LOCAL search_path TO pg_catalog`;
            await tx.unsafe(jobs[0]!.command as string);
          });

          expect(await countChanges()).toEqual({ old: 0, recent: 1 });
        } finally {
          await admin`DROP SCHEMA cron CASCADE`;
        }
      });
    });

    it('should keep a LilypadDbCache in sync without LISTEN', async () => {
      const cache = await LilypadDbCache.create({
        ttl: 60_000,
        gate,
        schema: usersSchema,
        sync: { strategy: 'changelog', pollInterval: 0 },
      });
      await cache.sqlCreate({ name: 'Ada', role: 'dev' });
      expect(await cache.getOrFetch(1)).toMatchObject({ role: 'dev' });

      await admin`UPDATE users SET role = 'admin' WHERE id = 1`;
      expect(await cache.getOrFetch(1)).toMatchObject({ role: 'admin' });

      await admin`INSERT INTO users (name) VALUES ('Grace')`;
      expect((await cache.getAll()).map((user) => user.name).sort()).toEqual(['Ada', 'Grace']);

      await admin`DELETE FROM users WHERE id = 1`;
      expect(await cache.getOrFetch(1)).toBeNull();

      await admin`TRUNCATE users`;
      expect(await cache.getAll()).toEqual([]);
      await cache.dispose();
    });

    it('should not query again the rows the cache wrote itself', async () => {
      const cache = await LilypadDbCache.create({
        ttl: 60_000,
        gate,
        schema: usersSchema,
        sync: { strategy: 'changelog', pollInterval: 0 },
      });
      await cache.getAll();
      const created = await cache.sqlCreate({ name: 'Ada', role: 'dev' });
      const updated = await cache.sqlUpdate({ id: created!.id, role: 'admin' });
      const queries = [
        vi.spyOn(gate, 'selectAllFromTable'),
        vi.spyOn(gate, 'selectFromTableByPrimaryKey'),
        vi.spyOn(gate, 'selectFromTableByPrimaryKeys'),
      ];
      try {
        expect(await cache.getAll()).toEqual([updated]);
        expect(await cache.getOrFetch(created!.id)).toEqual(updated);
        for (const query of queries) {
          expect(query).not.toHaveBeenCalled();
        }
      } finally {
        queries.forEach((query) => query.mockRestore());
        await cache.dispose();
      }
    });

    it('should let LISTEN and the changelog work together', async () => {
      const listened = vi.fn();
      await gate.addListener({ channel: 'cache_events', callbackId: 'both', callback: listened });

      await admin`INSERT INTO users (name) VALUES ('Ada')`;

      await vi.waitFor(() => expect(listened).toHaveBeenCalled());
      expect((await readAll()).changes).toHaveLength(1);
      await gate.removeListener('cache_events', 'both');
    });
  });

  describe('schema check', () => {
    const users = { table: 'users', primaryKey: 'id' };
    const codes = (result: Awaited<ReturnType<typeof checkLilypadSchema>>) =>
      result.problems.map((problem) => problem.code);

    it('should find nothing to fix in a database set up with the library SQL', async () => {
      const result = await checkLilypadSchema(gate, {
        tables: [users],
        notifyChannel: 'cache_events', // sent by the custom trigger of the test table
      });

      expect(result).toEqual({
        ok: true,
        problems: [],
        tables: [{ table: 'users', schema: 'public' }],
      });
    });

    it('should report a missing table', async () => {
      const result = await checkLilypadSchema(gate, {
        tables: [{ table: 'missing', primaryKey: 'id' }],
      });

      expect(codes(result)).toEqual(['missing-table']);
      expect(result.tables).toEqual([{ table: 'missing', schema: null }]);
    });

    it('should report a table without the changelog trigger, with the SQL that fixes it', async () => {
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      try {
        const options = { tables: [{ table: 'unwatched', primaryKey: 'id' }] };
        const result = await checkLilypadSchema(gate, options);
        expect(codes(result)).toEqual(['missing-changelog-trigger']);

        await admin.unsafe(result.problems[0]!.fix!);

        expect((await checkLilypadSchema(gate, options)).ok).toBe(true);
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should report a disabled changelog trigger', async () => {
      await admin`ALTER TABLE users DISABLE TRIGGER users_lilypad_update`;
      try {
        const result = await checkLilypadSchema(gate, { tables: [users] });

        expect(codes(result)).toEqual(['missing-changelog-trigger']);
        expect(result.problems[0]!.message).toContain('do not record UPDATE');
        expect(result.problems[0]!.message).toContain('disabled');
      } finally {
        await admin`ALTER TABLE users ENABLE TRIGGER users_lilypad_update`;
      }
    });

    it('should report a changelog trigger that fires only on replicas', async () => {
      await admin`ALTER TABLE users ENABLE REPLICA TRIGGER users_lilypad_delete`;
      try {
        const result = await checkLilypadSchema(gate, { tables: [users] });

        expect(codes(result)).toEqual(['missing-changelog-trigger']);
        expect(result.problems[0]!.message).toContain('do not record DELETE');
      } finally {
        await admin`ALTER TABLE users ENABLE TRIGGER users_lilypad_delete`;
      }
    });

    it('should accept the row trigger of version 3, and replace it with the statement triggers', async () => {
      await admin`CREATE TABLE legacy (id int PRIMARY KEY)`;
      await admin`
        CREATE TRIGGER legacy_lilypad_changes AFTER INSERT OR UPDATE OR DELETE ON legacy
        FOR EACH ROW EXECUTE FUNCTION lilypad_cache_changes_record('id')
      `;
      await admin`
        CREATE TRIGGER legacy_lilypad_truncate AFTER TRUNCATE ON legacy
        FOR EACH STATEMENT EXECUTE FUNCTION lilypad_cache_changes_record('id')
      `;
      try {
        const options = { tables: [{ table: 'legacy', primaryKey: 'id' }] };
        expect((await checkLilypadSchema(gate, options)).ok).toBe(true);
        await admin`INSERT INTO legacy VALUES (1), (2)`;

        await admin.unsafe(lilypadChangelogTriggerSql({ table: 'legacy', primaryKey: 'id' }));
        await admin`INSERT INTO legacy VALUES (3)`;

        const { changes } = await readLilypadChanges(gate, {
          tableName: 'legacy',
          since: { lookback: 60_000 },
        });
        expect(changes.map((change) => change.rowId)).toEqual(['1', '2', '3']);
        const [trigger] = await admin`
          SELECT count(*)::int AS count FROM pg_trigger
          WHERE tgrelid = 'legacy'::regclass AND tgname = 'legacy_lilypad_changes'
        `;
        expect(trigger!.count).toBe(0);
        expect((await checkLilypadSchema(gate, options)).ok).toBe(true);
      } finally {
        await admin`DROP TABLE legacy`;
      }
    });

    it('should report a table whose TRUNCATE is not recorded', async () => {
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      // The row trigger alone, as installed by version 2
      await admin`
        CREATE TRIGGER unwatched_lilypad_changes AFTER INSERT OR UPDATE OR DELETE ON unwatched
        FOR EACH ROW EXECUTE FUNCTION lilypad_cache_changes_record('id')
      `;
      try {
        const options = { tables: [{ table: 'unwatched', primaryKey: 'id' }] };
        const result = await checkLilypadSchema(gate, options);
        expect(codes(result)).toEqual(['missing-truncate-trigger']);

        await admin.unsafe(result.problems[0]!.fix!);

        expect((await checkLilypadSchema(gate, options)).ok).toBe(true);
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should report a changelog installed by version 2', async () => {
      await admin`COMMENT ON FUNCTION lilypad_cache_changes_record() IS 'lilypad-changelog:2'`;
      try {
        const result = await checkLilypadSchema(gate, { tables: [] });

        expect(codes(result)).toEqual(['outdated-changelog']);
        expect(result.problems[0]!.message).toContain('version 2');
        // Installed with notifyChannel: false, so the fix sends no notification either
        expect(result.problems[0]!.fix).not.toContain('pg_notify');
      } finally {
        await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
      }
    });

    it('should keep the notifications of an outdated changelog in its fix', async () => {
      await admin.unsafe(lilypadChangelogSql({ notifyChannel: "app'events" }));
      await admin`COMMENT ON FUNCTION lilypad_cache_changes_record() IS 'lilypad-changelog:3'`;
      try {
        const result = await checkLilypadSchema(gate, { tables: [] });

        expect(codes(result)).toEqual(['outdated-changelog']);
        expect(result.problems[0]!.fix).toBe(lilypadChangelogSql({ notifyChannel: "app'events" }));
      } finally {
        await admin.unsafe(lilypadChangelogSql({ notifyChannel: false }));
      }
    });

    it('should report a trigger that records another column than the primary key', async () => {
      const result = await checkLilypadSchema(gate, {
        tables: [{ table: 'users', primaryKey: 'name' }],
      });

      expect(codes(result)).toEqual(['wrong-trigger-primary-key']);
      expect(result.problems[0]!.message).toContain('"id"');
    });

    it('should report a table whose triggers send no notification on the channel', async () => {
      // The changelog trigger function of this suite sends none (notifyChannel: false)
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      await admin.unsafe(lilypadChangelogTriggerSql({ table: 'unwatched', primaryKey: 'id' }));
      try {
        const result = await checkLilypadSchema(gate, {
          tables: [{ table: 'unwatched', primaryKey: 'id' }],
          changelog: false,
          notifyChannel: 'cache_events',
        });

        expect(codes(result)).toEqual(['missing-notify-trigger']);
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should report a table whose triggers notify only some of INSERT, UPDATE and DELETE', async () => {
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      await admin`
        CREATE TRIGGER unwatched_cache_events AFTER UPDATE ON unwatched
        FOR EACH ROW EXECUTE FUNCTION notify_cache_events()
      `;
      try {
        const result = await checkLilypadSchema(gate, {
          tables: [{ table: 'unwatched', primaryKey: 'id' }],
          changelog: false,
          notifyChannel: 'cache_events',
        });

        expect(codes(result)).toEqual(['missing-notify-trigger']);
        expect(result.problems[0]!.message).toContain('only on UPDATE');
        expect(result.problems[0]!.message).toContain('not told about INSERT, DELETE');
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should accept notifications split across several triggers', async () => {
      await admin`CREATE TABLE unwatched (id int PRIMARY KEY)`;
      await admin`
        CREATE TRIGGER unwatched_insert AFTER INSERT ON unwatched
        FOR EACH ROW EXECUTE FUNCTION notify_cache_events()
      `;
      await admin`
        CREATE TRIGGER unwatched_update_delete AFTER UPDATE OR DELETE ON unwatched
        FOR EACH ROW EXECUTE FUNCTION notify_cache_events()
      `;
      await admin`
        CREATE TRIGGER unwatched_truncate AFTER TRUNCATE ON unwatched
        FOR EACH STATEMENT EXECUTE FUNCTION notify_cache_events()
      `;
      try {
        const result = await checkLilypadSchema(gate, {
          tables: [{ table: 'unwatched', primaryKey: 'id' }],
          changelog: false,
          notifyChannel: 'cache_events',
        });

        expect(result.ok).toBe(true);
      } finally {
        await admin`DROP TABLE unwatched`;
      }
    });

    it('should report a missing changelog', async () => {
      const result = await checkLilypadSchema(gate, {
        tables: [users],
        changelog: { table: 'other_changes' },
      });

      expect(codes(result)).toEqual(['missing-changelog', 'missing-changelog-trigger']);
      expect(result.problems[0]!.fix).toContain('CREATE TABLE IF NOT EXISTS "other_changes"');
      expect(result.problems[1]!.fix).toContain('EXECUTE FUNCTION "other_changes_record"');
    });

    it('should report a changelog installed by version 1, and upgrade it', async () => {
      await admin.unsafe(lilypadChangelogSql({ table: 'legacy_changes', notifyChannel: false }));
      // What version 1 installed: no schema column, no version comment
      await admin`ALTER TABLE legacy_changes DROP COLUMN table_schema`;
      await admin`COMMENT ON FUNCTION legacy_changes_record() IS NULL`;
      try {
        const options = { tables: [], changelog: { table: 'legacy_changes' } };
        const result = await checkLilypadSchema(gate, options);
        expect(codes(result)).toEqual(['outdated-changelog']);
        expect(result.problems[0]!.message).toContain('version 1');

        await admin.unsafe(result.problems[0]!.fix!);

        expect((await checkLilypadSchema(gate, options)).ok).toBe(true);
      } finally {
        await admin`DROP TABLE legacy_changes`;
        await admin`DROP FUNCTION legacy_changes_record()`;
      }
    });
  });

  describe('tables of the same name in different schemas', () => {
    beforeAll(async () => {
      await admin`CREATE SCHEMA archive`;
      await admin`CREATE TABLE archive.users (id int PRIMARY KEY, name text NOT NULL)`;
      await admin.unsafe(lilypadChangelogTriggerSql({ table: 'archive.users', primaryKey: 'id' }));
      // A second changelog, whose trigger function also sends notifications on cache_events. Its
      // trigger is created by hand: the generated one has the same name as the trigger above.
      await admin.unsafe(lilypadChangelogSql({ table: 'archive.changes' }));
      await admin`
        CREATE TRIGGER archive_users_notify AFTER INSERT OR UPDATE OR DELETE ON archive.users
        FOR EACH ROW EXECUTE FUNCTION archive_changes_record('id')
      `;
    });

    afterAll(async () => {
      await admin`DROP SCHEMA archive CASCADE`;
      await admin`DROP FUNCTION archive_changes_record()`;
    });

    beforeEach(async () => {
      await admin`TRUNCATE archive.users, archive.changes`;
      await admin`TRUNCATE lilypad_cache_changes`;
    });

    it('should read the changes of the table of the given schema only', async () => {
      await admin`INSERT INTO users (name) VALUES ('Ada')`;
      await admin`INSERT INTO archive.users (id, name) VALUES (7, 'old')`;
      const read = (tableName: string) =>
        readLilypadChanges(gate, { tableName, since: { lookback: 60_000 } });

      expect((await read('users')).changes.map((change) => change.rowId)).toEqual(['1']);
      expect((await read('public.users')).changes.map((change) => change.rowId)).toEqual(['1']);
      expect((await read('archive.users')).changes.map((change) => change.rowId)).toEqual(['7']);
    });

    it('should still return the rows recorded without a schema by version 1', async () => {
      await admin`
        INSERT INTO lilypad_cache_changes (table_name, row_id, op) VALUES ('users', '9', 'UPDATE')
      `;

      const { changes } = await readLilypadChanges(gate, {
        tableName: 'archive.users',
        since: { lookback: 60_000 },
      });

      expect(changes.map((change) => change.rowId)).toEqual(['9']);
    });

    it('should notify each row of a statement recorded by a changelog that notifies', async () => {
      await admin`CREATE TABLE archive.notified (id int PRIMARY KEY)`;
      await admin.unsafe(
        lilypadChangelogTriggerSql({
          table: 'archive.notified',
          primaryKey: 'id',
          changelogTable: 'archive.changes',
        })
      );
      const received: unknown[] = [];
      await gate.addListener({
        channel: 'cache_events',
        callbackId: 'statement',
        callback: (payload) => {
          const parsed = JSON.parse(payload as string) as { table: string };
          if (parsed.table === 'notified') {
            received.push(parsed);
          }
        },
      });
      try {
        await admin`INSERT INTO archive.notified VALUES (1), (2)`;

        await vi.waitFor(() => expect(received).toHaveLength(2));
        expect(received).toEqual([
          expect.objectContaining({ schema: 'archive', id: '1', op: 'INSERT' }),
          expect.objectContaining({ schema: 'archive', id: '2', op: 'INSERT' }),
        ]);
        expect(
          (
            await checkLilypadSchema(gate, {
              tables: [{ table: 'archive.notified', primaryKey: 'id' }],
              changelog: { table: 'archive.changes' },
              notifyChannel: 'cache_events',
            })
          ).ok
        ).toBe(true);
      } finally {
        await gate.removeListener('cache_events', 'statement');
        await admin`DROP TABLE archive.notified`;
      }
    });

    it('should resolve the schema of each table', async () => {
      const result = await checkLilypadSchema(gate, {
        tables: [
          { table: 'users', primaryKey: 'id' },
          { table: 'archive.users', primaryKey: 'id' },
        ],
      });

      expect(result.ok).toBe(true);
      expect(result.tables).toEqual([
        { table: 'users', schema: 'public' },
        { table: 'archive.users', schema: 'archive' },
      ]);
    });

    it('should not apply to a LilypadDbCache the notifications of the other schema', async () => {
      const cache = await LilypadDbCache.create({
        ttl: 60_000,
        gate,
        schema: usersSchema,
      });
      // Registered after the cache: when it sees a notification, the cache has applied it
      const seen: { schema?: string; op: string }[] = [];
      await gate.addListener({
        channel: 'cache_events',
        callbackId: 'archive-spy',
        callback: (payload) => void seen.push(JSON.parse(payload as string)),
      });
      try {
        const created = await cache.sqlCreate({ name: 'Ada', role: 'dev' });

        await admin`INSERT INTO archive.users (id, name) VALUES (1, 'old')`;
        await admin`DELETE FROM archive.users WHERE id = 1`;
        await vi.waitFor(() =>
          expect(seen).toContainEqual(expect.objectContaining({ schema: 'archive', op: 'DELETE' }))
        );

        expect(cache.get(1)).toEqual(created);
      } finally {
        await gate.removeListener('cache_events', 'archive-spy');
        await cache.dispose();
      }
    });
  });

  describe('singleton', () => {
    it('should create a new instance after the singleton is closed', async () => {
      const options = {
        connectionString: container.getConnectionUri(),
        listen: [],
        singleton: true as const,
        singletonIdentifier: 'LilypadDbGate.integration-singleton',
      };
      const first = await LilypadDbGate.create(options);

      expect(await LilypadDbGate.create(options)).toBe(first);

      await first.close();
      const second = await LilypadDbGate.create(options);

      expect(second).not.toBe(first);
      await second.close();
    });
  });

  describe('with LilypadDbCache', () => {
    it('should keep the cache in sync through cache_events notifications', async () => {
      const cache = await LilypadDbCache.create({
        ttl: 60000,
        gate,
        schema: usersSchema,
      });
      const created = await cache.sqlCreate({ name: 'Ada', role: 'dev' });
      expect(created?.id).toBe(1);

      await admin`UPDATE users SET role = 'admin' WHERE id = 1`;
      await vi.waitFor(() => expect(cache.get(1)).toEqual({ id: 1, name: 'Ada', role: 'admin' }));
      expect(cache.peek(1).type).toBe('hit');

      await admin`DELETE FROM users WHERE id = 1`;
      await vi.waitFor(() => expect(cache.get(1)).toBeNull());

      await admin`INSERT INTO users (name) VALUES ('Grace')`;
      expect(await cache.getAll()).toHaveLength(1);
      await admin`TRUNCATE users`;
      await vi.waitFor(async () => expect(await cache.getAll()).toEqual([]));

      await cache.dispose();
    });
  });
});
